### ISSUE TITLE
SSAO from Gshade Causing issues

### ISSUE THREAD

**Issue by Subrias** [DelvUI/DelvUI#1001]
Basically SSAO in the ghsade editor is helping add deeper shadows to the game. This is having the side effect of making the shadows show up through any UI mods i add using delvui. example: https://i.imgur.com/1UOvK9x.png It does it no matter which SSAO i add. Im assuming this is because your ui isnt on the same layer as the games actual ui so when GShade saves and reloads the UI, it isnt affecting yours. I tried looking and havent found another message about it, apologies if someone has already pointed this out and/or found a solution.

**Comment by Caliel666** [comment]
switch gshade to dxgi mode, or just rename the file in your game directory to dxgi.dll

**Comment by Subrias** [comment]
> 

Aesome, thank you.
