### ISSUE TITLE
[Bug]: Macro <target>/<t> does not work off of the party list

### ISSUE THREAD

**Issue by zbee** [DelvUI/DelvUI#1012]
### What are you trying to do?

In my macro, I have [`<t>` for the target](https://ffxiv.consolegameswiki.com/wiki/Macro#Placeholders), and want to hover over a person in the delvui party list, hit that macro, and have them be the target of the action.
In the normal party list, I can hover over a person in the party list OR hover over their character in the game.

### What is the expected behavior?

That I hover over a party member in the delvui party list, hit my macro using a `<t>` for the target, and the macro fires on that party member.

### What actually happened?

The `<t>` targeted action errors if my errors are enabled, and the action is used on myself - depending on the action.

### Suggested solution

I believe this involved adding [`<t>` macro targeting](https://ffxiv.consolegameswiki.com/wiki/Macro#Placeholders) support, and that's about all.
The clone `<target>` also does not work

### Logs

```shell
The `/ac`tion simply fails that there is no target specified, and most actions just run anyway but with myself as the target.
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Caliel666** [comment]
Make sure you are not using automatic mode when using macros


DelvUI supports 2 mouseover modes:
 - Automatic Mode: If your cursor is on top of a DelvUI unit frame or party frame, mouseover will be assumed automatically. This doesn't work with mouseover macros or other mouseover plugins. If you wish to use this mode, just use your regular skills without <mo> macros and they should work right away.
 - Normal Mode: DelvUI frames will behave like any mouseoverable in-game elements (party list, focus target, etc). You can use mouseover macros or other mouseover plugins with this mode.

**Comment by zbee** [comment]
Thank you, thank you - that fixed it. So many settings, I've clearly not checked through enough ha
