### ISSUE TITLE
[Suggestion]: Make decimal health percentage digit count consistent

### ISSUE THREAD

**Issue by BerkeBat** [DelvUI/DelvUI#1013]
### What's your suggestion?

Currently when using the decimal health percentage tag for something like unitframes, whenever the percentage ends up on a whole number, there is no decimal .0 shown. For example it will go from 75.1% to 75% then to 74.9%. Obviously the value is correct but if there is other text in the label, the final digit disappearing and reappearing causes the rest of the text to move left and right all the time. Not a huge issue but a small QOL change would be to change it so that it goes from 75.1% to 75.0% then to 74.9%.

I think 100% should still stay without the .0 and I'm not sure about 0%, that's probably fine too since it will only reach that once and won't cause the text movement during combat

**Comment by vond82** [comment]
I don’t agree that this is an improvement, but could possibly add it as a separate texttag
