### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LefeinWhoTookMyName** [DelvUI/DelvUI#1015]
### What are you trying to do?

Crash when using execute macro from the macro list.
Warrior
Macro /ac “Raw Intuition”

or /ac “Inner Release”
tracked it down to only Delvui being installed. Using the trackers for the Warrior class.
The crash is an immediate client close. Reproducible repeatedly with only Devlui turned on. Executing from the macro list was how I was able to repeatedly reproduce the issue. Didn’t try in combat. Note a Nascent Flash @focus macro in combat never caused this to happen. Unable to reproduce with any other plug-in combination provided Delvui is off. Sometimes takes up to 3 tries. By the time I’ve tested the macro using “execute macro” from the macro list the fourth time I’ve managed to reproduce the crash without fail. Hope this helps. I didn’t want to write a bug report but I couldn’t find an easy way to DM.

### What is the expected behavior?

Not crashing.

### What actually happened?

It crashed the client.

### Suggested solution

Probably something with the tracking whether sanity check or otherwise I have no idea.

### Logs

```shell
There are no errors whatsoever it’s an immediate client runtime termination to desktop.
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by LefeinWhoTookMyName** [comment]
Thank your for your hard work. I hate reporting bugs to the public. Sorry about this.

**Comment by vond82** [comment]
I will see if I can reproduce this later, but theres really no benefit (quite the opposite) to using macros like that so i dont quite see the reason for them. The crash does seem odd however.

**Comment by LefeinWhoTookMyName** [comment]
What an R3 L3 macro has to do with reporting a crash caused by your content I fail to understand.

Thanks for the critique.

**Comment by Tischel** [comment]
Post your dalamud.log please

**Comment by vond82** [comment]
I tried reproducing this and I can use macros like that just fine on my warrior without ever causing a crash. I tried with keybound macro and executing straight from the macropage and neither would crash the game. But yes, we'll need a dalamud.log file like Tischel said. It's found in %AppData%\XIVLauncher\dalamud.log
