### ISSUE TITLE
[Suggestion]: Debuffs/Buffs on targets target - Sizing of own de-buffs

### ISSUE THREAD

**Issue by me1337me** [DelvUI/DelvUI#1017]
### What's your suggestion?

Hello everyone,

let me first thank you for this awesome UI!

For me as a healer, I often have targeted the tank (or temporarily any other group member) and use a /tt for dmg spells.
To check whether i applied my debuffs already on the enemy (targets target) would be great to see it on even that unit frame.

Also an option for not just adding a border but having it bigger than other (de)buffs would be great!

Thanks a lot!

**Comment by vond82** [comment]
Size for own debuffs is unlikely to ever happen (not saying it never will, but unlikely to), but you do have the enemy list where you see your own debuffs on the target (and not others). 

As for buffs/debuffs on ToT that should be doable in the future I guess, but also not really a priority for reason given above + the fact that with DelvUI automatic mouseover you never have to target anything other than the boss anyway as a healer :)

**Comment by me1337me** [comment]
thanks for your swift reply.

oh wow, i was missing the mouseover function so hard and didnt know, its already there :D

Thanks a lot!
