### ISSUE TITLE
[Suggestion]: MNK Forms bar split

### ISSUE THREAD

**Issue by DJFarr** [DelvUI/DelvUI#1020]
### What's your suggestion?

Change the MNK Forms bar to 3 split bars with colour and text, where only one is active at a time.
This should give a much better visual representation of what form the player is currently in at a glance.

I think it would be important to replicate the average/standout colours of each of the stance's Buff icons, to help differentiate them at a quick glance.

The small bars could also be timer bars, to indicate the amount of time left in the stance, as opposed to just solid blocks, but this might be best as an optional feature (I don't need it myself, my stance will never really stay for longer than 2 GCDs).

I mocked it up to see how it would look:
![I](https://user-images.githubusercontent.com/16067714/154014138-3e41bf8d-76c9-42e8-85fa-cf1ff06e92eb.jpg)
![II](https://user-images.githubusercontent.com/16067714/154014146-f1ad3e52-4ceb-4393-b754-08655008f78c.jpg)
![III](https://user-images.githubusercontent.com/16067714/154014155-30037455-9562-4ef8-b241-8a587235198f.jpg)

As mentioned by Vond, this would also help solve the translation issue as the current Form names are hardcoded.

**Comment by kaedys** [comment]
+1 to this.  The existing form bar is not particularly helpful, especially since all 3 forms are displayed in the same color.  A bar where the form is indicated both by color and by _physical position on the bar_ would be immensely more helpful.

**Comment by DJFarr** [comment]
This would still be great to have, if anyone picked up the task

**Comment by kaedys** [comment]
Not stale.  The current stance bar is, imo, nearly useless.  UI elements, especially when part of the central HUD, should give rapid at-a-glance information.  You should not need to read the text and then mentally cross-reference it with which slot in the rotation that name corresponds to.  UI is about rapid-access information, and color and position are both _critical_ elements of that.  Having a bar that indicates in only an instant glance which form you're in would be exceptionally useful, and the current stance bar doesn't do that at all.

**Comment by Tischel** [comment]
Planning on this for next release: https://github.com/DelvUI/DelvUI/pull/1075

**Comment by kaedys** [comment]
Oh, that's excellent! Much appreciated @Tischel!

**Comment by Tischel** [comment]
Implemented in v1.2.1.0
