### ISSUE TITLE
[Suggestion]: Option to show "Soft Target" on enemy list

### ISSUE THREAD

**Issue by Sloop0** [DelvUI/DelvUI#1023]
For us controller users, we can hold LB and press up/down on the d-pad to scroll through the enemy list, but this only makes them our "soft" target until we press A. The DelvUI enemy list doesn't show soft targets, unlike the standard enemy list, which makes this feature basically unusable with DelvUI. If an option to show soft targets in some way on the enemy list could be added, it would be extremely helpful for controller users.

**Comment by Tischel** [comment]
Implemented in v1.1.1.0
