### ISSUE TITLE
[Suggestion]: Hide DelvUI via hotkey

### ISSUE THREAD

**Issue by Denixerianer** [DelvUI/DelvUI#1024]
### What's your suggestion?

I know that there are options to hide the delvui elements while sheathed weapons and i love it! But i would also love to see an option to hide the delvui elements via hotkey for example for when i want to take a screenshot while my weapon is unsheathed. This is for me the biggest negative of this mod but still love it <3

**Comment by gingertonik** [comment]
you can macro /delvui (show|hide|toggle) and then bind that macro to a keybind, would that work?

**Comment by Spanglish1337** [comment]
> you can macro /delvui (show|hide|toggle) and then bind that macro to a keybind, would that work?

Ohhh making '/delvui toggle' as a macro would work! Perfect, thank you!
