### ISSUE TITLE
[Bug]: TPie: When the only items are nested rings, it forces one to be a quick action (which can't be opened).

### ISSUE THREAD

**Issue by valerieTurlington** [DelvUI/DelvUI#1040]
### What are you trying to do?

I added five nested rings to my ring, and this caused one of them to be forced as quick action. Given that there is no checkbox available for these, I could not remove it as a quick action.

I _think_ this somehow happened because I initially had gear sets added, and then I removed them all and added nested rings.

### What is the expected behavior?

If a nested ring is a quick action, it will allow me to open after hovering.

Or, nested rings disabled as quick actions.

### What actually happened?

I ended up with a nested ring as a quick action, which then could not be opened.

### Suggested solution

Add some sort of check when items are added/removed so that a quick action isn't currently a nested ring. Or restrict the quick action to a "setter" which will do nothing if a nested ring is passed in. Or just anywhere else in the process, add a check that will automatically remove a nested ring as the quick action if it was somehow set accidentally.

You do you, it's an awesome plugin.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by gingertonik** [comment]
you should post this on the TPie github. https://github.com/Tischel/TPie/issues

**Comment by valerieTurlington** [comment]
Ah! I meant to! So sorry
