### ISSUE TITLE
[Bug]: Mana bar doesn't show up in PvP for classes that don't have mana in PvE

### ISSUE THREAD

**Issue by Sloop0** [DelvUI/DelvUI#1042]
### What are you trying to do?

Since every class now has mana in PvP, I'd like to be able to see my mana, even as classes that don't otherwise use mana.

### What is the expected behavior?

The mana bar configuration should work and properly display my mana bar.

### What actually happened?

When I'm on a class that doesn't use mana in PvE, for example WAR, my mana bar will not display. I've adjusted settings, switched profiles, etc. with no change. As soon as I switch to a class that does use mana in PvE, the mana bar reappears.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by gingertonik** [comment]
Please make sure the player mana bar is enabled under Mana Bars > Player

Then enable the generic mana bar in the job specific hud config. to use your example for WAR as shown: 
![image](https://user-images.githubusercontent.com/91795517/164340336-ebf3931a-d5f3-4adb-80f7-c0335c60f07d.png)

No special consideration is given for PvP by DelvUI.

**Comment by Sloop0** [comment]
I didn't think to check that Job Specific Bars menu, that was the problem. Thank you!
