### ISSUE TITLE
[Bug]: Enemy Cast Bar disappear delay

### ISSUE THREAD

**Issue by Absolutioo** [DelvUI/DelvUI#1061]
### What are you trying to do?

I see a delay for the enemy cast bar disappearence.  They dont disappear the same moment as the vanilla one.

https://user-images.githubusercontent.com/57093597/167421600-2c4b5053-b590-4666-bb27-1a559e54aa86.mp4

It only happens for the "ENEMY" cast bar if i target myself for example and cast a spell. the delv and vanilla cast bar disappear at the same time.
The issue can be reproduced with any enemy that has a cast. I had several friends test it and they all had the delay as well.

### What is the expected behavior?

I think it should be expected that the Delvui enemy cast bar and vanilla cast bar disappear at the same time.

### What actually happened?

see above

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v1.1.2.0
