### ISSUE TITLE
[Suggestion]: Add Moon icon as an option to the experience bar.

### ISSUE THREAD

**Issue by imgidedin** [DelvUI/DelvUI#1065]
### What's your suggestion?

Currently, it is not possible to know if we are on a sanctuary or not.

**Comment by Zeffuro** [comment]
Might be possible if we copy the right glyph range / use axis font. This would also be useful/nice to get the official enemylist order letters and partylist numbers

**Comment by Tischel** [comment]
Added in v 1.2.1.0 (to be released soon)
