### ISSUE TITLE
[Bug]: party cooldowns: tactician has wrong cd

### ISSUE THREAD

**Issue by Delta87** [DelvUI/DelvUI#1066]
### What are you trying to do?

The cooldown of tactician is wrong.
![mch_cd](https://user-images.githubusercontent.com/17047430/168730936-b39d8242-66ea-4dca-8e84-71e02d383a5e.png)

### What is the expected behavior?

The cooldown should be 90 seconds

### What actually happened?

the actual cooldown is 120 seconds

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by shaunwoodruff** [comment]
Level 88 trait reduces it to 90 from 120.

**Comment by Shuggler** [comment]
This is true for samba too, and guessing mch ^^

**Comment by Zeffuro** [comment]
I tried to work on this a bit but don't have it working yet. If anyone wants to take a look at a suggested way of fixing it: https://github.com/Zeffuro/delvui/commit/c879b5521b34e5e03c21f8990c1be39958fdd013

**Comment by Zeffuro** [comment]
Tischel has implemented a fix https://github.com/DelvUI/DelvUI/commit/8184861722d78242da3c281f2deca3ab16afb963

**Comment by Tischel** [comment]
Fixed in v1.2.1.0
