### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Nightbird827** [DelvUI/DelvUI#1069]
### What are you trying to do?

Does not display Player Mana Bar, no matter what settings are selected.

### What is the expected behavior?

Mana bar is displayed

### What actually happened?

Mana bar does not display

### Suggested solution

Uh..fix it? Idk. Lol

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by gingertonik** [comment]
what job are you on?

did you enable the generic mana bar option in the Job Specific Bars config of that job?

are you playing BLM or DRK which have custom built mana bars as part of their Job Specific Bars?

are you sure the mana bar isn't off screen due to the x,y positioning of it?

**Comment by Nightbird827** [comment]
I am on BLM. I actually turned the Job Specific Bar off as I didn't really like it. Is it possible to have just a mana bar? Is that what generic bar is? 

I suppose this is a user error issue rather than a bug. Lol

**Comment by gingertonik** [comment]
i can only imagine it is because you are using the vanilla job hud, because the BLM mana bar is about as full featured as a BLM player could want. yes, enable the generic mana bar as shown here 
![image](https://user-images.githubusercontent.com/91795517/171760853-b930bdca-b693-4d81-a480-1e45783904eb.png)

**Comment by Nightbird827** [comment]
Alright. That should definitely fix it then. Maybe I'll give the actual class bar another shot eventually. Just seemed a little too busy and confusing for my tastes. 

Thanks for the help!
