### ISSUE TITLE
[Bug]: Mouse not working seemingly random times if the plugin is enabled

### ISSUE THREAD

**Issue by Grimvh** [DelvUI/DelvUI#1070]
### What are you trying to do?

When the plugin is enabled, a strange bug occurs at seemingly random times (I have no clue on what is triggering this bug). Neither the left nor the right mouse button reacts (I'm able to move the cursor itself). Only full game restart solves the problem.

### What is the expected behavior?

Mouse buttons should work as usual. (camera, menu, etc)

### What actually happened?

At random intervals the plugin will bug the mouse.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Keeping issue alive since people are still reporting this.
Still haven't been able to find a way to reproduce this issue.

**Comment by Solanya** [comment]
It usually happens for me if the party is disbanded while hovering one of the party frames. The UI then stops responding to clicks and I need to restart. Hoping it helps.
