### ISSUE TITLE
[Bug]: Unexpected tool line-breaks at non-standard Dalamud Global Font Scale

### ISSUE THREAD

**Issue by Nox13last** [DelvUI/DelvUI#1072]
### What are you trying to do?

Set the font size in Dalamud to be 14pt, as 12pt is too small for me to easily read on a 4K display.
I want to state that this worked without complaint last week (before the big patches).

As far as I know, the DelvUI version I have is latest. 1.1.4.1.

### What is the expected behavior?

The tooltip should be properly formatted.
Pictured below is the tooltip when Dalamud's global font size is at 12pt.
![image](https://user-images.githubusercontent.com/1292492/179306834-5e27c983-3d9d-499b-abbf-4c268bbda966.png)

This, but slightly larger.

### What actually happened?

Pictured below is the tooltip when Dalamud's global font size is at 14pt.
![image](https://user-images.githubusercontent.com/1292492/179306910-83f2b3e6-5c39-4b75-8ba2-ca3d3d9f8a10.png)

This seems to occur irrespective of the font settings (unless the text size is absurdly, illegibly small).

### Suggested solution

Less text padding in the tooltips.
Configurable text padding in the UI elements.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

### Addendum (t+7 days):

The Dalamud volunteers (the **_goat place_ Discord**) insist that this is an issue with plugins "not handling UI Scaling correctly". Whatever this means.

**Comment by Nox13last** [comment]
The problem is still occurring, and it occurs even if DelvUI is the only plugin installed.
The global font size is a feature built into Dalamud as an accessibility helper. That other tickets have been opened and closed while a concern about DelvUI becoming incompatible with an accessibility helper has languished is a bit troubling.
DelvUI has steered me true this past year, but if it comes down to a choice between "I need to be able to read my tooltips" and "I need to be able to read _everything else_" that's not a decision I can abide DelvUI forcing upon me.

**Comment by Tischel** [comment]
Fixed in v1.1.5.0

**Comment by Nox13last** [comment]
Almost. Iron Will (the example in the original ticket) is fixed...
![image](https://user-images.githubusercontent.com/1292492/181264076-e0f0d4e8-a917-4c08-879f-8d78faee6062.png)

...but this one (seen in Containment Bay P1T6 (Sophia)) is still symptomatic.
![image](https://user-images.githubusercontent.com/1292492/181263965-cd9ff019-12b3-4c55-87f8-4a3d386bca8d.png)

**Comment by Tischel** [comment]
I'll try to fix again in v1.2.0.0 (probably to be released in the next couple of days).
Will leave the ticket open for your confirmation.

**Comment by Nox13last** [comment]
Of the images above, Defiance (as an example) shows clearly. The only one in that list I can't test is Eternal Doom, but the others show properly.
![image](https://user-images.githubusercontent.com/1292492/181827798-1642d60a-0e69-4f81-9715-08b6347eafd1.png)

Alas, in the Preview Pane, the issue is manifesting elsewhere.
![image](https://user-images.githubusercontent.com/1292492/181827482-abf4c375-9e07-49c5-92fc-b511a1dc437a.png)
![image](https://user-images.githubusercontent.com/1292492/181827580-f23b4bfa-97da-4073-a1cd-224d1d37f2b8.png)
![image](https://user-images.githubusercontent.com/1292492/181827603-10736131-c925-444a-82fb-99a86ced0dde.png)

Current version is DelvUI v1.2.0.1. I noticed in the DelvUI Git, there's an entry for 1.2.1.0, but it's not available through the repos I have. Has this one been released (and I'm not using up-to-date repos), or is it not deployed yet?

Thank you for your ongoing efforts.

**Comment by Tischel** [comment]
Hmm this time I wasn't able to reproduce on v1.2.0.1
To be completely honest, I'm kinda lost now.

I tested with:
Global Font = 14pt
Tooltips Font = Roboto Light 24p

**Comment by Nox13last** [comment]
**I will amend this comment as I find new information.**

The issue persists.
![image](https://user-images.githubusercontent.com/1292492/181905963-bec7a550-68e2-4773-986e-ba51891771f8.png)

...however, turning on "Show Status Effect IDs" or "Show Source Name" fixes it! (in the Preview mode, there's no source.)
![image](https://user-images.githubusercontent.com/1292492/181905991-8bf7c555-b19f-458b-94b5-917132ee048f.png)
![image](https://user-images.githubusercontent.com/1292492/181906004-6c9c5623-da27-4dbf-94a8-6b890a559742.png)
![image](https://user-images.githubusercontent.com/1292492/181906064-132896e2-8e7e-4a0f-9635-f45e04e4a307.png)
![image](https://user-images.githubusercontent.com/1292492/181906205-e17cc882-31ec-47ec-905e-50888853b9da.png)
Even in situations that would cause a line-break (such as the inclusion of the source's name), it behaves appropriately.

**Comment by Tischel** [comment]
There's some weird stuff going on with the code that calculates the size of the text.
Both the actual font and the global font scale affect those calculations.
That's why changing the font yields different results.
