### ISSUE TITLE
[Bug]: Hotbar display command spam during NPC dialogue

### ISSUE THREAD

**Issue by kaedys** [DelvUI/DelvUI#1074]
### What are you trying to do?

Talking to an NPC that has dialogue.

### What is the expected behavior?

NPC dialogue

### What actually happened?

Rapid spam of `The command "/hotbar display <#> off" is unavailable at this time` appears in the chat window.  This spam starts as soon as the NPC dialogue window appears (ie. the chat bubble at the bottom with what they're saying and the arrow prompt to continue), and stops as soon as the NPC dialogue window disappears (including going into a menu from the NPC, such as the menu for turning in the weekly journal at Khloe).

<img width="402" alt="HrJQT79OEp" src="https://user-images.githubusercontent.com/9020449/181672415-61650521-a777-4b17-931b-1bd593d36848.png">

My settings are to hide the hotbar outside of combat, except in duties and when my weapons are out.  However, this spam occurs even when the hotbar is already hidden by not being in a duty and not having my weapons out when I talk to the NPC. 
 Also happens if I _do_ have my weapons out when I talk to them, and the hotbar is successfully hidden due to my weapons being automatically sheathed before the NPC dialogue starts.

<img width="651" alt="ST8kYsk6aL" src="https://user-images.githubusercontent.com/9020449/181672421-f048e88f-bb3e-4161-9378-e4dd6db35d64.png">

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed v1.2.0.1
