### ISSUE TITLE
[Linux]: Low FPS when using DelvUI

### ISSUE THREAD

**Issue by joker-119** [DelvUI/DelvUI#1082]
### What are you trying to do?

Use the plugin.

Even with everything individually disabled (all unit frames, all cast bars, all job specific bars, etc) I lose 35-45% of my fps when delvui is enabled. 
An interesting tidbit, clicking the DelvUI "hide HUD" button restores my FPS, and turning it back off drops it again, even though nothing in DelvUI is actually enabled.

### What is the expected behavior?

Not lose half my FPS

### What actually happened?

FPS drops from 70-75 to 30

### Suggested solution

Find and fix the source of the FPS drop. I don't even know where to begin with debugging, otherwise I would do it and PR the fix myself.

### Logs

```shell
No errors present in dalamud.log
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by gingertonik** [comment]
can you confirm that no part of the delvui hud is clipping an edge of the screen? this will cause an issue that halves your fps.

**Comment by joker-119** [comment]
I will double check, but is that still an issue even if those elements are disabled?

**Comment by joker-119** [comment]
![ffxiv_08092022_181129_492](https://user-images.githubusercontent.com/10914157/183788790-45eefb4b-2985-4320-9dbb-bf4feb01393c.png)
It doesn't appear that anything is clipping off screeen

**Comment by gingertonik** [comment]
no, but they only need to clip a pixel.

**Comment by joker-119** [comment]
Interestingly, I can't find where my player mana bar is. I've set it's anchor to center, position is 0,0 and it's not anchored to the unit frame, but it's just nowhere to be found

**Comment by joker-119** [comment]
> no, but they only need to clip a pixel.

If this isn't an issue for frames that are enabled, then it wouldn't make sense to be my issue when everything is disabled.
I've tried 7 different profiles now (incase any of them had something that was clipping) and they all have the same result.
Notably, intentionally making a frame clip the edge of the screen, shows no change in behavior for FPS.

**Comment by Tischel** [comment]
What OS do you have?

**Comment by Tischel** [comment]
DelvUI is known to have terrible FPS on Linux.
We have no devs on Linux that can look into it. One of the moderators in our discord uses Linux and has had issues with FPS before. You might wanna try joining the discord to talk with them.

https://discord.com/invite/xzde5qQayh

**Comment by joker-119** [comment]
Ah, ok. Hopefully this is something I can fix within DelvUI and PR it for Linux players, and not an issue in WINE itself.
