### ISSUE TITLE
[Bug]: job specific bars broken

### ISSUE THREAD

**Issue by 22116** [DelvUI/DelvUI#1086]
### What are you trying to do?

Display job specific bar on ninja

### What is the expected behavior?

Everyting is fine according to real skill data as it was before update 6.2

### What actually happened?

Ninki bars don't work at all.
Huton bar shows random numbers. For example it shows full bar with value as 52625 when Huton is disabled and 69458 when ability was activated.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by azy2** [comment]
I'm seeing this bug as well

**Comment by telinit** [comment]
Huton bar is broken for me as well. Seems like the number increases each time you use Huton.
![image](https://user-images.githubusercontent.com/4019549/186771419-ac849bc4-a0ab-4730-a194-4859dd460f60.png)
![image](https://user-images.githubusercontent.com/4019549/186771624-08fbb016-8c79-4e5b-829d-d75cc42a8271.png)

**Comment by yurisim** [comment]
@telinit , looks like [Tischel](https://github.com/DelvUI/DelvUI/commits?author=Tischel) fixed it in the interim by overriding the ninja addresses with his own. :) check out this commit
https://github.com/DelvUI/DelvUI/commit/59c1ac81ab92140c024566ae36f0985e69acc9b5

**Comment by Tischel** [comment]
Fixed in v1.4.1.0
