### ISSUE TITLE
[Bug]: Crashing upon 'default' option being selected

### ISSUE THREAD

**Issue by Endbringer7** [DelvUI/DelvUI#1089]
### What are you trying to do?

Whenever I try to reset DelvUI, it crashes the game and forces me to restart it.

### What is the expected behavior?

A window with a few options: restart, restart without plugins, exit game.

### What actually happened?

I attempted to reset the DelvUI so that I could build a UI from the ground up. Whenever I do this, DelvUI causes the game to crash, requiring a restart. It also does this when I import user DelvUI profiles.

### FFXIV Update

- [x] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Close the game then go to `%AppData%\XIVLauncher\pluginConfigs` and delete the `DelvUI` folder.
That should fix all your issues.
