### ISSUE TITLE
P5S cast bars

### ISSUE THREAD

**Issue by ozmone** [DelvUI/DelvUI#1090]
Don't know if it's an issue with P6S+ but in P5S "tail to claw" or "claw to tail" are both displaying nonsensical strings, which i assume is the ID of the skill or some such

**Comment by Tischel** [comment]
Known issue.
Spells and debuffs are encrypted on new savage tiers / ultimates.

The fix will take a while,

**Comment by Denixerianer** [comment]
same for p6s

**Comment by hintxiv** [comment]
> same for p6s

Same answer as above.

**Comment by Tischel** [comment]
Fixed in v1.4.2.2
