### ISSUE TITLE
[Help wanted]: only show "???" on Chinese client.

### ISSUE THREAD

**Issue by P0sce3fa** [DelvUI/DelvUI#1091]
### What's the issue?

I did add Chinese fonts and also turned on Chinese support, but it still doesn't display properly, I would be very grateful if you can help me

![image](https://user-images.githubusercontent.com/17513790/188261114-64556a03-2eb9-483e-825e-195f19105e79.png)
![image](https://user-images.githubusercontent.com/17513790/188261130-5ce1a9e3-c4d7-4c5e-b01e-1db9ea6228b8.png)
![image](https://user-images.githubusercontent.com/17513790/188261176-79b6f01c-50ad-4bc0-ba86-8a5b57a43506.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Did you actually set the font in the label?

**Comment by Sunfury-art** [comment]
Does the landlord solve the problem of garbled code？

**Comment by Sunfury-art** [comment]
> ### What's the issue?
> I did add Chinese fonts and also turned on Chinese support, but it still doesn't display properly, I would be very grateful if you can help me
> 
> ![image](https://user-images.githubusercontent.com/17513790/188261114-64556a03-2eb9-483e-825e-195f19105e79.png) ![image](https://user-images.githubusercontent.com/17513790/188261130-5ce1a9e3-c4d7-4c5e-b01e-1db9ea6228b8.png) ![image](https://user-images.githubusercontent.com/17513790/188261176-79b6f01c-50ad-4bc0-ba86-8a5b57a43506.png)
> 
> ### FFXIV Update
> * [x]  I have confirmed that I have the latest version of XIVLauncher and DelvUI.

Does the landlord solve the problem of garbled code？I got the same trouble.

**Comment by Sunfury-art** [comment]
Does the landlord solve the problem of garbled code? I had the same problem.

**Comment by Zeffuro** [comment]
Follow this

https://user-images.githubusercontent.com/4972345/190943199-c9128a84-691c-4575-b844-3761341ae780.mp4
