### ISSUE TITLE
[Suggestion]: Party Frames: sort player by role, instead of position 1

### ISSUE THREAD

**Issue by kaedys** [DelvUI/DelvUI#1092]
### What's your suggestion?

For the party frames, the only options at the moment are default sort, in which case the player is sorted first followed by role-based sorting (tanks > healers > DPS), or a fixed-position override.  I'd like to have my tanks, healers, and DPS in reliable positions (TTHHDDDD), however, and since I play multiple jobs (and roles), I can't used a fixed position for that unless I want to maintain 3 separate DelvUI profiles, for the 3 roles, that differ _only_ in the fixed position assignment.  The position override also doesn't work well with light parties for any position but 1.  For example, if I select position 3 for the first healer slot in a full party, now my order in a light party is Tank, DPS, Me (healer), DPS.

Ideally, this would be an additional option, mutually exclusive with the existing Player Order Override, which lets you select role-based sorting.  If selected, you would be placed in the frame list at the top of your respective role (with the roles sorted as they currently are), rather than position 1 overall, leading to the 3 roles occupying reliable positions on the frames.  Honestly, since the existing default, with the player sorted first, is mechanically equivalent to a position override of 1, you could even make the above role-based sorting the _default_ (ie. with position override unchecked), and players that want to be in position 1 could simply enable the override option.  Could even have it enabled by default for all existing users that do not have an override set, to avoid disruption.

**Comment by Tischel** [comment]
Added a "First of my role" setting in v1.4.3.0
