### ISSUE TITLE
[Suggestion]: True North buff duration tracking

### ISSUE THREAD

**Issue by Qunka724** [DelvUI/DelvUI#1097]
### What's your suggestion?

First of all thanks for this plugin, it's indispensable as a healer! I was just thinking it'd be nice if you could track True North's buff duration on a bar. There may be a way to take this idea even further, like tracking the number of stacks you have and the cooldown of it, but really I'm just looking for a visual indication on when the effects of True North will expire. Maybe it could be an option in the Job Specific Bars setting?

Thanks,

**Comment by Tischel** [comment]
You might wanna look into XIVAuras for something like this.
Will probably not be implemented in DelvUI.
