### ISSUE TITLE
[Bug]: Enemy List Cast Bar does not show unless enemy is targeted

### ISSUE THREAD

**Issue by obscenevaccine** [DelvUI/DelvUI#1099]
### What are you trying to do?

Within the Enemy List, when an enemy is casting, it does not show their cast bar unless the enemy is targeted.  When enemy is not targeted there is no change/no cast bar.

### What is the expected behavior?

When an enemy is casting, the cast bar should show regardless of whether they are targeted or not.  This allows for the ability to select the correct casting enemy to stun/CC/etc.

### What actually happened?

Currently, when an enemy is casting, and they are not targeted, it does not show the cast bar in the enemy list.

I have compared this to the in game "built-in" enemy list which does show the cast bar when enemies are casting.

Additionally, there are times when "all of a sudden" it will briefly show a cast bar for untargeted enemies, but that is very infrequent and seemingly random.  I feel that this was working successfully prior to the latest update, but I cannot confirm exactly when it stopped working.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v1.4.5.1

**Comment by k0etsu** [comment]
Noticing this behavior again using 1.4.5.1. Some instances behave as expected with other instances hiding cast bars. 

Video confirmation:
https://streamable.com/99euw6
