### ISSUE TITLE
[Bug]: Tooltips are not wrapped correctly

### ISSUE THREAD

**Issue by dooks** [DelvUI/DelvUI#1103]
### What are you trying to do?

![image](https://user-images.githubusercontent.com/3730143/207706879-7a56b56b-137d-49ed-8e5e-c34cbe7088ef.png)

### What is the expected behavior?

Tooltips to be displayed correctly, and the entire description visible.

### What actually happened?

Text wrapping seems to be incorrect, and the rest of the tooltip description is cutoff.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by yujiaw21** [comment]
can confirm i have the same bug

**Comment by dooks** [comment]
Should be fixed now.
