### ISSUE TITLE
[Help wanted]: The CastBar is moved to the upper left on the next startup when this plugin is updated.

### ISSUE THREAD

**Issue by RanshiinSama** [DelvUI/DelvUI#1111]
### What's the issue?

As the title says, if you update this plugin, quit the game once and start again, the CastBar will move to the upper left corner.
Is this a bug in DelvUI? Or is it a specification?
This phenomenon is definitely related to DelvUI, as I never witness this phenomenon while DelvUI is disabled.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Heinzen** [comment]
Steps to replicate:

# Update DelvUI to a newer version
# Open HUD Layout configuration

Notice that the castbar is on the correct spot

# Cast any spells
# Open HUD Layout configuration

Notice that the castbar has been moved to x0y0

Behavior is only seen when updating DelvUI and casting a spell for the first time

**Comment by RanshiinSama** [comment]
Thank you for your reply.
I am aware of the replicate and run it every time it is updated.
In short, "the phenomenon of the CastBar moving to x0y0 after an update is a specification", I understand.

**Comment by Heinzen** [comment]
No worries. Was adding replication steps to assist the devs.

**Comment by Tischel** [comment]
Should be fixed in v2.1.3.0
