### ISSUE TITLE
[Bug]: delvui party brame buff bug

### ISSUE THREAD

**Issue by Nefesis93** [DelvUI/DelvUI#1112]
### What are you trying to do?

my goal was to have buffs on pary frame starting on top left, then top right, then bottom left and then bottom right. I was tring to mix up settings but i ended up assuming that the "fill row first" check dows not work correctly with the padding and the "right and down" option

### What is the expected behavior?

expected behaviour is that buffs, with the correct settings follow the positions

### What actually happened?

with the fill row first + right and down settings together even with various iterations of padding buff always end up in a straight line, overcoming the limitation frame of the buff

### Suggested solution

with my low experience my suggestion for the fixx might be to check that the buff dont go out of the space they should be limited to i feel like thats the main issue but again not sure

### Logs

```shell
i dont take error logs so i cant help in that regard
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v1.6.1.0
