### ISSUE TITLE
[Bug]: Empty display result via Job tag in mana bar text

### ISSUE THREAD

**Issue by HASTJI** [DelvUI/DelvUI#1113]
### What are you trying to do?

If we select in **Mana Bar** menu in **Label** section **Text** and write |job| - it will display nothing, just empty string, but JOB is one of many available tags in drop-down menu.

![изображение](https://user-images.githubusercontent.com/6943544/218580397-0c0c39ef-bcbb-4f92-80ad-0f1a2d573764.png)

### What is the expected behavior?

There must be a name of the job of player, in which manabar is that text-tag writed.

### What actually happened?

Empty string without any job name

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
This will only happen in preview mode
