### ISSUE TITLE
[Bug]: All Nameplates disappear in Critical engagements (Bozja/Zadnor) when the camera gets too close to the edge of arena

### ISSUE THREAD

**Issue by Denixerianer** [DelvUI/DelvUI#1116]
### What are you trying to do?

Its all in the title. Also dont know where else to leave this so i'll leave it here: Nameplates are a very welcome addition i like

### What is the expected behavior?

Not disappear

### What actually happened?

Disappear

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Known issue. This can re be reproducible in multiple ways.
It's the expected result due to the limitations we have to deal with for this feature.

Will not get fixed for now. Maybe in the future I'll figure out a way to improve it for cases like this.
