### ISSUE TITLE
[Help wanted]: Nameplates clipping/displaying over windows

### ISSUE THREAD

**Issue by chaosxeloc** [DelvUI/DelvUI#1118]
### What's the issue?

I still have nameplates clipping over specific menus despite altering occlusion and window clipping settings.

![DelvUI](https://user-images.githubusercontent.com/117740799/219537561-9596fe6a-509e-4511-912e-45792e87ea4e.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Can you test with window clipping on "Full" or "Hide" ?
Performance mode doesn't work well with nameplates.
