### ISSUE TITLE
[Bug]: NPC nameplate issue with occlusion

### ISSUE THREAD

**Issue by ZezaReignhalt** [DelvUI/DelvUI#1123]
### What are you trying to do?

See the nameplate of NPCs while Occlusion Mode is on.

### What is the expected behavior?

Nameplate should be visible.

### What actually happened?

Nameplate is not visible even tho NPC nameplate is enabled.

![2023-02-19 22_00_27-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/220006538-04a253a8-1143-4637-bb37-babf1005b276.png)
![2023-02-19 22_01_00-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/220006539-0a28ad2d-60cd-4135-a190-c3d4a57fc6b8.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by ZezaReignhalt** [comment]
as an addition.  it does show the nameplate if occlusion mode is off.  but it also shows all nameplates within range through walls.

**Comment by Yueh72** [comment]
I got the same thing with the last update. It worked before.

**Comment by Tischel** [comment]
Addressed in v1.6.1.0 with the new Occlusion Type setting.
Read the patch notes when it gets released please.
