### ISSUE TITLE
[Bug]: New Nameplates do not work with released island minions

### ISSUE THREAD

**Issue by kbrighton** [DelvUI/DelvUI#1124]
### What are you trying to do?

Am on Island Sanctuary and the new nameplates work for all NPCs save for the released minions.

### What is the expected behavior?

The NPC setting for the nameplates would work for the released minions, or the Minion settings.

### What actually happened?

No new nameplates for the released minions

### Suggested solution

Have the released minions in the island sanctuary follow the same rules as the NPCs.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v1.6.1.0
