### ISSUE TITLE
[Suggestion]: Adding textures to bars

### ISSUE THREAD

**Issue by crowley-re** [DelvUI/DelvUI#1128]
### What's your suggestion?

Adding textures to any bar that has the potential to hold them : Unit Frame Bars (Health, Mana & Casting), Job Specific Bars..

A preview of the idea on player's health bar, using the cloud.tga texture

![1](https://user-images.githubusercontent.com/128557158/226783303-9237f1a4-e663-4581-89bd-b946bfb958e2.png)
![1](https://user-images.githubusercontent.com/128557158/226779401-9d361a8c-fbf4-48ad-9271-4aacb6a29a3b.png)

**Comment by Tischel** [comment]
Feature is being tested internally.
Will most likely be released on version 2.0.0.0.

No ETA as of yet.

**Comment by Tischel** [comment]
Added in v2.0.0.0
