### ISSUE TITLE
[Bug]: Default font doesnt support special characters

### ISSUE THREAD

**Issue by Necroskillz** [DelvUI/DelvUI#1129]
### What are you trying to do?

![image](https://user-images.githubusercontent.com/346477/232333359-c5cbe2a2-5520-4b38-b78a-34069ec208b6.png)

### What is the expected behavior?

Should be `Fate Calibration α` / `Fate Calibration β`

### What actually happened?

Question mark instead of greek letter.

### Suggested solution

Obviously using a different font is a possibility, but not sure how feasible that is, could break other stuff. 

Maybe just replace these two symbols with A and B and add exceptions if they add anything like that into the game again?

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
You can add custom fonts in Misc > Fonts.

**Comment by Necroskillz** [comment]
I know, but my point is that the default should be able to correctly display the cast name.
