### ISSUE TITLE
[Help wanted]:  skill cast on frame click

### ISSUE THREAD

**Issue by YakudzaKY** [DelvUI/DelvUI#1130]
### What's the issue?

He there. Very good plugin but need help.
Can i bind some heal's skills on party list click? i.e. heal teammate by clicking on his healthbar in party frames?

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by gingertonik** [comment]
DelvUI has no function for this and it is out of scope for this plugin.

**Comment by Tischel** [comment]
Closest thing is the Automatic Mouseover mode that you can enable in Misc > HUD Options.
