### ISSUE TITLE
[Bug]: Right click doesnt work sometimes

### ISSUE THREAD

**Issue by KaladinMekhar** [DelvUI/DelvUI#1133]
Hi,

I've been facing this for a few months now. And I am pretty sure its Delvui causing the issue because I've turned off every plugin except this one. The issue is - sometimes the Right click doesnt work for camera control. 

The issue starts off like this
1. When the right click is released, the mouse cursor doesnt appear. The right click seems to be stuck and moving the mouse without right clicking moves the camera
2. Then clicking both Left and Right clicks simultaneously makes the cursor appear again
3. But now the right click doesnt work anymore and I cant turn the camera
It always occurs in the above order.

It happens randomly only in PVP and dungeons. I've never noticed it outside instances. It sometimes auto-fixes itself after a few minutes and sometimes I have to restart the game.

**Comment by Tischel** [comment]
I am aware of this issue, it's just hard to fix.
It is more likely to happen to you if you're using DelvUI nameplates with health bars.

I still don't have a way to reproduce this 100% time, and that's the main reason why I haven't been able to fix it.

**Comment by KaladinMekhar** [comment]
No problem. It is a rare issue and I've learned to work around it I think. Also FYI, I am not using DelvUI nameplates with health bars. I only have DelvUI Player Debuffs and Target Buffs/Debuffs on. And I have them on a very big icon size.

**Comment by Tischel** [comment]
Tentative fix in v2.0.0.0

Please let me know if it's still happening.

**Comment by KaladinMekhar** [comment]
Hi, it is still happening. My version is 2.0.2.1. As before it is rare. But I am unable to tell if its happening more or less frequent when compared to pre v2. As before I am only using Target Buffs/Debuffs. And I have them on a very big icon size.
