### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hsramm** [DelvUI/DelvUI#1134]
### What are you trying to do?

Nameplates are not working at all but everything else seems to be. Settings were not changed from 6.3 to 6.4 and the nameplates were working in 6.3.

### What is the expected behavior?

N/A

### What actually happened?

N/A

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v1.7.1.0.
Use "Simple" Occlusion Mode for now.
