### ISSUE TITLE
[Bug]: Faerie Gauge doesn't work

### ISSUE THREAD

**Issue by Tegual** [DelvUI/DelvUI#1135]
### What are you trying to do?

When playing Scholar, using Delvui and turning on the Faerie Bar, it does not track the Faerie Gauge, it says at 0 the entire time and the bar does not fill up.

### What is the expected behavior?

Every time you use an aetherflow ability the faerie guage gains 10 energy.

### What actually happened?

The faerie gauge does nothing at present.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v1.7.1.1
