### ISSUE TITLE
Incompatibility with Material UI

### ISSUE THREAD

**Issue by Will-ALVIDI** [DelvUI/DelvUI#1138]
### What's the issue?

I'm trying to use Delv UI with Material UI.

The problem is that Delv UI, even with HUD Elements at their lowest strata levels, seem to be always at a higher strata level than what Material UI provides.
This results in Delv UI HUD elements overlapping everything from Material UI.

Have I missed something ? Is there a way to fix it ?

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Enable Misc > Winwdow Clipping

**Comment by Will-ALVIDI** [comment]
Thank you for your quick answer, seems to work.
