### ISSUE TITLE
[Bug]: Nameplate position settings affect the wrong components of the nameplate

### ISSUE THREAD

**Issue by krom-ja** [DelvUI/DelvUI#1142]
### What are you trying to do?

I am attempting to adjust the position of the "Name Label", "Title Label", and "Health Bar" components under Nameplates. The bug applies to the "Player" nameplate. Some of the reported issues affect all nameplates, but not all of them.

Adjusting certain components seems to move the wrong components, or in other cases, other unintended components will also move with the component you are trying to move.

### What is the expected behavior?

Adjusting the y-coordinate of the "Title Label" should move only the Title.
Adjusting the y-coordinate of the "Name Label" should move only the Name.
Adjusting the y-coordinate of the "Health Bar" should move only the Health Bar.

### What actually happened?

Adjusting the y-coordinate of the "Title Label" moves the position of the "Name Label".
Adjusting the y-coordinate of the "Name Label" moves the position of the "Title Label".
Adjusting the y-coordinate of the "Health Bar" moves all components of the Nameplate, and not just the health bar.
-  The health bar issue specifically affects all player-related nameplates. The title and name label move with the health bar.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Labels are automatically anchored to the health bar.
So moving the health bar will move the labels, as expected.

Regarding the name and title labels affecting each other, you probably have the "Swap Name and Title labels when needed" enabled.
This settings makes it so if you have a prefix title, the label that is higher y-position wise will have the title, and the lower one will have the name. For a suffix title, it'd be the opposite.

From what I can see all the interactions you described are intended.
Let me know if I missed something.
