### ISSUE TITLE
[Bug]:  Target marker not showing up in party list

### ISSUE THREAD

**Issue by lalayanlala** [DelvUI/DelvUI#1143]
### What are you trying to do?

I want to display the target marker in the party list

### What is the expected behavior?

A target marker appears in the party list

### What actually happened?

Even if you attach a target marker to a member, the target marker does not appear in the party list

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Are you talking about the signs on top of people's heads? They work for me...

Can you provide some screenshots to see what's going on?

**Comment by Tischel** [comment]
Nevermind, they are actually not working.
Will be fixed in v1.7.1.5
