### ISSUE TITLE
[Bug]: Chat message errors when joining/leaving Chocobo races

### ISSUE THREAD

**Issue by bayta-88** [DelvUI/DelvUI#1144]
### What are you trying to do?

Joining a chocobo race.

### What is the expected behavior?

No error messages appearing in chat.

### What actually happened?

Error messages appear in chat due to DelvUI trying to show/hide action bars when the player is joining/leaving a duty but being unable to do so because action bar visibility states can't be changed during a chocobo race. The game is perfectly playable and the only minor annoyance is these messages appearing, so I know it's a pretty minor issue.

### Suggested solution

Maybe it would be possible to filter out the duties that correspond to chocobo races so DelvUI doesn't try to toggle action bar visibility states in those instances.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.0.0.0
