### ISSUE TITLE
[Suggestion]: Capability of sorting buffs/debuffs in party frames by their remaining time

### ISSUE THREAD

**Issue by bayta-88** [DelvUI/DelvUI#1145]
### What's your suggestion?

Sometimes in raid fights a player needs to check the debuffs on other players to know what to do and the order in which they expire is important. For instance, in p10s during the bonds mechanic the player might need to see if they should first stack and then spread, or viceversa.
For these cases it would be useful to be able to have the debuffs in the raid frames sorted based on their remaining duration so the player can know at a glance which action he needs to perform first without needing to compare their durations manually. It is relatively minor but I believe that in the middle of a raid fight it can be a big QoL improvement. This could also be extended to personal buffs/debuffs.

**Comment by Tischel** [comment]
Added in v2.0.0.0
