### ISSUE TITLE
[Bug]: DelvUI sometimes drops focus from active Dalamud window

### ISSUE THREAD

**Issue by ChaosInfinited** [DelvUI/DelvUI#1147]
### What are you trying to do?

Typing using Chat2 or typing in any other Dalamud window

### What is the expected behavior?

Active text field should stay focused

### What actually happened?

O̶n̶l̶y̶ ̶w̶h̶e̶n̶ ̶h̶a̶v̶i̶n̶g̶ ̶D̶e̶l̶v̶U̶I̶ ̶e̶n̶a̶b̶l̶e̶d̶ ̶a̶n̶d̶ ̶i̶t̶'̶s̶ ̶`̶v̶i̶s̶i̶b̶l̶e̶`̶,̶ ̶a̶l̶l̶ ̶D̶a̶l̶a̶m̶u̶d̶ ̶w̶i̶n̶d̶o̶w̶s̶ ̶(̶i̶n̶c̶l̶u̶d̶i̶n̶g̶ ̶C̶h̶a̶t̶2̶)̶ ̶l̶o̶s̶e̶ ̶f̶o̶c̶u̶s̶ ̶a̶t̶ ̶r̶a̶n̶d̶o̶m̶,̶ ̶w̶h̶i̶c̶h̶ ̶r̶e̶s̶u̶l̶t̶s̶ ̶i̶n̶ ̶u̶s̶i̶n̶g̶ ̶h̶o̶t̶b̶a̶r̶s̶ ̶s̶k̶i̶l̶l̶s̶/̶i̶t̶e̶m̶s̶,̶ ̶m̶o̶v̶e̶m̶e̶n̶t̶ ̶e̶t̶c̶.

W̶a̶s̶n̶'̶t̶ ̶a̶b̶l̶e̶ ̶t̶o̶ ̶p̶i̶n̶p̶o̶i̶n̶t̶ ̶w̶h̶a̶t̶ ̶e̶x̶a̶c̶t̶l̶y̶ ̶m̶a̶k̶e̶s̶ ̶i̶t̶ ̶h̶a̶p̶p̶e̶n̶,̶ ̶s̶o̶m̶e̶t̶i̶m̶e̶s̶ ̶i̶t̶'̶s̶ ̶c̶o̶m̶p̶l̶e̶t̶e̶l̶y̶ ̶r̶a̶n̶d̶o̶m̶,̶ ̶s̶o̶m̶e̶t̶i̶m̶e̶s̶ ̶I̶'̶m̶ ̶a̶b̶l̶e̶ ̶t̶o̶ ̶r̶e̶c̶r̶e̶a̶t̶e̶ ̶i̶t̶ ̶w̶h̶e̶n̶ ̶m̶o̶v̶i̶n̶g̶ ̶m̶y̶ ̶c̶u̶r̶s̶o̶r̶ ̶a̶ ̶l̶o̶t̶,̶ ̶m̶a̶k̶i̶n̶g̶ ̶s̶u̶r̶e̶ ̶i̶t̶ ̶h̶o̶v̶e̶r̶s̶ ̶o̶t̶h̶e̶r̶ ̶p̶l̶a̶y̶e̶r̶s̶ ̶o̶r̶ ̶o̶t̶h̶e̶r̶ ̶U̶I̶ ̶e̶l̶e̶m̶e̶n̶t̶s̶.̶ ̶S̶o̶m̶e̶t̶i̶m̶e̶s̶ ̶i̶t̶ ̶h̶a̶p̶p̶e̶n̶s̶ ̶e̶v̶e̶r̶y̶ ̶s̶e̶c̶o̶n̶d̶,̶ ̶s̶o̶m̶e̶t̶i̶m̶e̶s̶ ̶i̶t̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶h̶a̶p̶p̶e̶n̶.̶

With Mana Bars -> Player -> Label -> Enabled, hovering over some skills/actions of which tooltip window overlaps the Label, results in loosing focus from active Dalamud window

Same happens when I hover over a buff for a tooltip, if tooltips are disabled, the focus is not being dropped.

How to reproduce:
1. Have Chat2 or any other Dalamud window with text field opened and active
2. Have Mana Bars -> Player -> Label -> Enabled
3. Hover cursor over skill of which tooltip hovers over Mana Bar Label
4. Focus from active window should be lost

### Suggested solution
I've asked a friend to install DelvUI and test it for himself, but it didn't happen to him, which means it has to be some specific setting causing it, will post it if I find it.

EDIT
After disabling Mana Bars it stopped happening
When Mana Bars -> Player -> Label -> Enabled are active and I hover on skill of which tooltip covers mana bar label, it drops the focus.

Tried moving item/skill tooltips into a fixed position, while it fixed the issue on hovering over some skills, the issue is still there if I hover on any of my active buffs.

### Logs

```shell
No errors, no warnings, nothing shows up in logs when this happens
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by PieOrCake** [comment]
I am also experiencing this issue, and disabling mana bar labels does not rectify it for me. The only thing that fixes the focus loss issue is to completely disable DelvUI and use the stock interface, which is less than ideal.

**Comment by Tischel** [comment]
I appreciate the detailed repro steps.
This seems to be directly related to the Window Clipping feature.
I'll have to investigate.

**Comment by Tischel** [comment]
Nevermind, I found the issue.

Fixed in v2.0.0.0 (no ETA)

**Comment by ChaosInfinited** [comment]
Hey @Tischel! Thanks for fixing the issue, it indeed fixed the issue when tooltips overlap the mana bar's label, however hovering over active buffs (which brings their tooltips up) still results in the same. :(

It only happens with DelvUI buff icons, stock ones don't cause it.

Should I open another issue for that?

**Comment by Tischel** [comment]
That's fixed on v2.0.1.0 (releasing today)

**Comment by ChaosInfinited** [comment]
Awesome, thanks! :)
Have a great weekend!

**Comment by PieOrCake** [comment]
After a week of testing, I confirm that the bug has indeed been fixed. Thank you very much to the dev.
