### ISSUE TITLE
[Help wanted]: Auto Switch UI 

### ISSUE THREAD

**Issue by krgault** [DelvUI/DelvUI#1149]
### What's the issue?

I having issues where the UI won't switch using VudUI for specific jobs. I have auto-switch turned on and jobs selected. For some reason it will on use the last string imported. I'm sticking to the DPS for now until either I can figure this out or get some help with what I may be doing wrong .

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
I tested the auto switch feature for profiles and it seems to be working fine.
Please provide detailed steps to reproduce the issue.
