### ISSUE TITLE
[Suggestion]: Don't show () when the source is empty on tooltips.

### ISSUE THREAD

**Issue by imgidedin** [DelvUI/DelvUI#1155]
### What's your suggestion?

![image](https://github.com/DelvUI/DelvUI/assets/19570528/b925f0a1-85ff-47b4-9930-c9e87aad15ad)

It would be nice to remove the empty `()` from the tooltips when no source is found for it, like in the example screenshot.

**Comment by Tischel** [comment]
Fixed in v2.0.1.0
