### ISSUE TITLE
[Suggestion]: Allow CTRL + LMB to input values on the Party Cooldown > Cooldowns Tracker

### ISSUE THREAD

**Issue by imgidedin** [DelvUI/DelvUI#1156]
### What's your suggestion?

![image](https://github.com/DelvUI/DelvUI/assets/19570528/36ba3d94-d0c1-403c-a6b3-223f99ddfd9c)

I am not sure if it is possible or not, but being able to press CTRL + Left Mouse Button to be able to insert a number, instead of having to slide it would improve its functionality a bit.

**Comment by Tischel** [comment]
Added in v2.0.1.0
