### ISSUE TITLE
[Suggestion]: Missing Gunbreaker No mercy for Party Cooldown Tracker

### ISSUE THREAD

**Issue by imgidedin** [DelvUI/DelvUI#1157]
### What's your suggestion?

![image](https://github.com/DelvUI/DelvUI/assets/19570528/4398e345-bb60-4863-b87d-9f6e9607acbd)

![image](https://github.com/DelvUI/DelvUI/assets/19570528/f10f7afc-2d65-4db9-abdc-6f7ba44af087)

**Comment by Tischel** [comment]
Added in v2.0.1.0
