### ISSUE TITLE
[Suggestion]: Option to disable specifically right-click on nameplates

### ISSUE THREAD

**Issue by kaedys** [DelvUI/DelvUI#1164]
### What's your suggestion?

I really like the ability to click on the new nameplates to select that target, but if the nameplates are set to be interactable, they also eat right-clicks from the mouse, despite not actually doing anything when right-clicked.  This interferes with right-click-drag to rotate the camera.  It can also occasionally get in a state where, if you right click to start rotating and your mouse ends up on top of one of the nameplates after that camera rotation, the right mouse _unclick_ will not register, and your mouse will be stuck controlling the camera even without right click held down (until you right click again elsewhere).

It'd be amazing if an option could be added (or it just always work like that, it _could_ be considered a bug) to disable this right-click behavior, where it intercepts the right-click and prevents it from being used to control the camera.

**Comment by Tischel** [comment]
Not possible, sadly.

**Comment by kaedys** [comment]
Darn.  Well, I'll just have to live with then being non-interactable, then, I think, interfering with the camera just torpedoes it for me =(  Appreciate the response, though.

**Comment by Sundava** [comment]
If you're feeling adventurous, you comment out the lines 304 to 307 in `InputsHelper.cs` to restore the right click to rotate camera and compile the addon yourself:
https://github.com/DelvUI/DelvUI/blob/develop/DelvUI/Helpers/InputsHelper.cs#L304-L307

I haven't noticed anything breaking, but it's not something I'd call "safe".
