### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sehnder** [DelvUI/DelvUI#1165]
### What are you trying to do?

Change Requiescat bar fill direction

### What is the expected behavior?

If I change the fill direction to up, it will fill upward.

### What actually happened?

It appears that whether or not up and down always fill as if fill down were selected, and fill left and fill right always as if fill right were selected.

### Suggested solution

Atonement fill is working fine in the paladin "module" (and elsewhere) so probably just some tiny typo somewhere. 

### Logs

```shell
I don't have logs, but I have a GIPHY you can watch to confirm the issue! https://giphy.com/gifs/tT4oYxQ38K5zBbd3fx/fullscreen

Also wanted to say thanks for the work on all the FFXIV addons. Can't imagine playing without them!
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.0.3.1
