### ISSUE TITLE
[Bug]: castbar slidecast window doesn't adjust to fill direction

### ISSUE THREAD

**Issue by jtoya85** [DelvUI/DelvUI#1167]
### What are you trying to do?

I have adjusted my ui to the point where my castbar is vertical filling from the bottom up. 

### What is the expected behavior?

I would've figured the slidecast window would follow the direction of the bar filling.

### What actually happened?

The slidecast window within the castbar does not adjust with the fill direction. the slidecast still shows as if the cast bar was filling like vanilla from the left to right.
![Untitled](https://github.com/DelvUI/DelvUI/assets/90115330/3b6f1c24-4c3a-4047-b4ef-7846c67c481a)

### Suggested solution

with my extremely limited knowledge of computer coding I would apply the section that governs the fill direction into the slidecast window, thereby hopefully having the slidecast properly display if the user changes the fill direction of the bar.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by jtoya85** [comment]
I cannot say if/when this became an issue. it was back on September 18th that I changed my ui around. I had asked on the Discord for help or to at least bring this to someone's attention but the lack of replies since then and no in-game update leads me to believe that the issue wasn't seen, so here I am to hopefully get someone to see this and maybe help.

**Comment by Tischel** [comment]
Fixed in next week's release for patch 6.5 (v2.1.0.0)
