### ISSUE TITLE
[Bug]: Issue with Regional Number Format for some locales

### ISSUE THREAD

**Issue by Sundava** [DelvUI/DelvUI#1169]
### What are you trying to do?

Using the setting "Regionale Number Format" displays a `?` character instead of the proper separator for some locales, such as `fr-FR`.

The problem was introduced in commit 9cc0fcf4c3b3da47057870e104c39e2063cc87f4 when using the current locale to format numbers.

### What is the expected behavior?

Thousands separator should be a space for the locale `fr-FR`

### What actually happened?

A `?` character is displayed instead of a space as a separator.
![image](https://github.com/DelvUI/DelvUI/assets/7022870/e8a9bdfb-8d4f-4891-9439-86c8a7876bce)

Example with the option unchecked:
![image](https://github.com/DelvUI/DelvUI/assets/7022870/94888904-204d-450d-bf54-b42d3ce048e0)

### Suggested solution

Kiloformat properly returns `4 214` with ` ` as a thousands separator, so I'm guessing this is something to do with how the space sign is interpreted when displaying the number itself.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
It's an issue with the font.
The separator character looks like a space but it's actually a different character that this font doesn't have, so a "?" is displayed instead.
