### ISSUE TITLE
Profiles tab missing?

### ISSUE THREAD

**Issue by KWild666** [DelvUI/DelvUI#1170]
### What's the issue?

Hello - Dalamud updated for me when I logged in today, and now the entire DelvUI profiles tab is missing and the profile reset to a default state. Is there anything I can do to fix this/restore my profiles?

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
https://github.com/DelvUI/DelvUI/wiki/DelvUI-Troubleshooting
