### ISSUE TITLE
[Bug]: UTF-8

### ISSUE THREAD

**Issue by ErickShnaider** [DelvUI/DelvUI#1172]
### What are you trying to do?

When using text other than Latin, the characters "????" appear instead of being displayed.
For example, when using client localization, where non-Latin names are used in utf-8 encoding, the name of the target looks like this
![ru](https://github.com/DelvUI/DelvUI/assets/148807633/3629ada7-d92e-4b9b-8c60-782168ad0571)

### What is the expected behavior?

With the original game files everything is fine. Meanwhile, the complexity lies in the encoding that the plugin uses. The creators of my localization of the game client assured me that the text in their localization and in the client’s original one uses UTF-8, but the plugin probably has a different encoding. They know the problem, but they cannot influence other people's code
![eng](https://github.com/DelvUI/DelvUI/assets/148807633/db1bed88-45be-4839-a05b-f44c2af938c3)

### What actually happened?

the plugin reads names not in UTF-8

### Suggested solution

add UTF-8 support to the plugin... probably

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
You need to use fonts that contain the characters you're trying to use.
You can add custom fonts to DelvUI in Customization > Fonts.

This has nothing to do with encoding or UTF-8.

**Comment by ErickShnaider** [comment]
this was the first thing I tried to do. I specified a folder with regular fonts (Windows/font), specified a regular font (arial), used it to write the target text, but nothing worked

**Comment by Tischel** [comment]
Added Cyrillic characters support in v2.1.1.0
Go to Customization > Fonts > Enable Cyrillic to use it (may need a game restart to apply).

**Comment by ErickShnaider** [comment]
![image](https://github.com/DelvUI/DelvUI/assets/148807633/821c40f6-b9d2-4052-9ae4-716b427f9aff)
I updated Delvui, installed Cyrillic support, and rebooted the game. The result is the same.
I can’t understand: what am I doing wrong?

**Comment by endervad** [comment]
Can we re-open this issue please? The fix didn't actually fix the issue, there are still question marks instead of names despite Cyrillic support being turned on.

**Comment by ErickShnaider** [comment]
For clarity, this is roughly what “target bar” looks like in both situations I’m talking about
![eng](https://github.com/DelvUI/DelvUI/assets/148807633/505e6448-4298-4d02-9fd0-d23bb560dc1c)
![ru](https://github.com/DelvUI/DelvUI/assets/148807633/b32edd0a-9b45-454a-b8a4-16d021e741fa)

**Comment by Tischel** [comment]
Fixed in v2.1.1.1
