### ISSUE TITLE
[Bug]: DelvUI No Profile Tab and Opening DelvUI Config or DevlCD config freezes whole computer 

### ISSUE THREAD

**Issue by the9thresident** [DelvUI/DelvUI#1175]
### What are you trying to do?

configure DevlUI or DelvCD 

### What is the expected behavior?

there should be a place for Profiles in the config and configs should not cause a total computer freeze

### What actually happened?

there is no place for profiles under DelvUI config and opening either DelvUI config or DelvCD config freezes entire computer to the point of having to use the kill switch

### Suggested solution

maybe how tell me how to get the corrupted files off my computer for a fresh install? I have uninstalled and reinstalled it and it's not working. Have also uninstalled and reinstalled the launcher 

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
https://github.com/DelvUI/DelvUI/wiki/DelvUI-Troubleshooting
