### ISSUE TITLE
[Bug]: Nameplate's layout 

### ISSUE THREAD

**Issue by Malkom** [DelvUI/DelvUI#1178]
### What are you trying to do?

Display nameplate with lowest layout.

### What is the expected behavior?

Open a window like settings or character and don't see nameplate over it.

### What actually happened?

I see nameplate over other frames like settings, character panel, etc...

![DelvUI_Nameplate_FF14](https://github.com/DelvUI/DelvUI/assets/441034/4a6990f1-3eb3-49b6-aa4e-96d4f0dc3837)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Misc > Window Clipping

![image](https://github.com/DelvUI/DelvUI/assets/6404136/af2fd6da-452e-49bb-a83a-9e28e785731c)
