### ISSUE TITLE
[Bug]: Party Cooldowns: Bloodwhetting and Heart of Stone don't account for their downgraded / upgraded versions

### ISSUE THREAD

**Issue by Mardraced** [DelvUI/DelvUI#1182]
### What are you trying to do?

In the Party Frames, and cool down frames, I'm trying to track both Bloodwhetting and Raw Intuition(when downgraded) for Warriors, and both Heart of Stone, and Heart of Corundum(Upgraded Heart of Stone)

### What is the expected behavior?

Bloodwhetting should become Raw Intuition in the cool down tracking when below level 82, 

Heart of Stone should become Heart of Corundum in the cool down tracking from level 82.

### What actually happened?

When downsynced below 82, Bloodwhetting no longer becomes tracked on the Party Cool downs
When above level 82, Heart of Stones cool down tracking does not begin when Heart of Corundum is used.

### Suggested solution

Perhaps have both as traceable options, with the downgraded versions (Raw Intuition and Heart of Stone) being filtered out when Level 82 and Above, 
and the upgraded versions (Bloodwhetting and Heart of Corundum) filtered out when level 81 and blow.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.2.0.10
