### ISSUE TITLE
[Help wanted]: cant show dead ally's name on partyframes

### ISSUE THREAD

**Issue by firtb2014** [DelvUI/DelvUI#1185]
### What's the issue?

when I set up my party frames,I noticed there was only "[dead]" on a dead ally's frame,I couldnt kown who he was.
and no matter which setting of name label I try ,his name dont show.
what should I do

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Uncheck `Party Frames > Icons > Player Status > Hide Name When Showing Status`

**Comment by firtb2014** [comment]
it works,thank you

> Uncheck `Party Frames > Icons > Player Status > Hide Name When Showing Status`
