### ISSUE TITLE
[Suggestion]: 2.2.0.0 PCT Gauge Adjustments 

### ISSUE THREAD

**Issue by ryrael** [DelvUI/DelvUI#1196]
### What's your suggestion?

For reference initially I thought it would be best to include the UI I'm running (modified vond profiles) - think it'll help with visuals
![image](https://github.com/DelvUI/DelvUI/assets/64334167/85514d93-220d-49ab-ac63-6fa1d80140a9)
I (personally) don't want or need to see the creatures I have on my canvas, only my active motif, I track this on my bar, and know when I'll next have moogle/madeen ready - thus I put landscape & weapon motif over the top of where they'd be on the creature gauge element
I'm in the discord, username is ryan003 if you wanna chat about anything
~~apologies for scuffed formatting~~

# Palette gauge 
## subtractive indicator ISSUE
- Indicator for subtractive palette on palette gauge when gauge <50
   - Indicator currently only shows when gauge >0
 
![image](https://github.com/DelvUI/DelvUI/assets/64334167/95354d2e-79a4-4d15-951e-c5b34bca5238)
50/100 gauge without subtractive

![image](https://github.com/DelvUI/DelvUI/assets/64334167/75220e5b-09d6-4bce-9fb9-34c990ce553d)
50/100 gauge with subtractive
![image](https://github.com/DelvUI/DelvUI/assets/64334167/e261f56f-3a91-432b-9ecf-837dcc4002c1)
0/100 gauge with subtractive

I worded this horrendously, so I'll yap:
The purple indicator currently only shows IF subtractive palette was cast at either 75/100 or 100/100 gauge 
If gauge is less than 50 and subtractive palette is active i.e. it was cast at 50/100, the purple indicator does not show

## suggestion
- show in chunks as default setting

# hammer time 
- Fill up the hammer time bar when striking muse is ready

# paint gauge 
- when monochrome tones active/have black paint, put black paint on the centre of the paint gauge (where 3rd paint is)
   + better visibility

OR
use an indicator similar to red mage's dualcast if black is available, in between the two chunks for the palette gauge (if this is chosen to be in the default profile) 
![mspaint_q6YUCMMhW6](https://github.com/DelvUI/DelvUI/assets/64334167/fa6f25b1-e6fb-4486-a6dc-80ed29457a91)
maybe looks a bit scuffed, and takes up a lot of room 

OR X2 
If monochrome tones status = true 
Paint gauge heavily darkened 
(probably more appropriate to do myself with DelvCD)

# Creature canvas
- separate creature motif stock from its depictions and moogle/madeen indicators 
 + allows better tracking of which motifs are currently stocked
 + having them separate will be disorientating compared to standard gauge 
PERSONALLY
I don't think you need to track moogle/madeen, but this probably doesn't apply to people unfamiliar with the job because it's more of a "i know i'll get moogle/madeen after wing/fang" 
i.e. it's probably best there is an option to keep depictions 

# Other suggestions
- the vertical stack would be getting a bit too big, but a tracker for the 5 stacks of hyperphantasia after starry muse could maybe be a thing...I guess this could just be a number indicator on the bar for landscape motif (won't look very clean, buuuut...I don't know what the best alternative would be)

**Comment by Zeffuro** [comment]
@Tischel Anything from this that we want or has already been implemented since?
