### ISSUE TITLE
[Bug]: Mouse Over not working

### ISSUE THREAD

**Issue by zbee** [DelvUI/DelvUI#1198]
### What are you trying to do?

Trying to use Mouse Over on party members, but it is not working, despite working on the actual party list HUD element.

### What is the expected behavior?

I expect when hovering over a party member in the DelvUI that mouse-over macros/plugins work.

### What actually happened?

It acted as though I was not hovering over anyone.
The Mouseover setting is still enabled, and party members' bars have their hover-over effect applied, but still nothing.

### Logs

```shell
No errors present.
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI (2.2).

**Comment by fshnchpz** [comment]
DelvUI > Misc > Mouseover > Automatic Mode enabled

**Comment by YakudzaKY** [comment]
i also have this trouble. Automatic mode is doesn't fit because macros or redirect plugin  does not recognize frames as mouseover

**Comment by YakudzaKY** [comment]
before downtrail all worked correctly

**Comment by Tischel** [comment]
Fixed in next release.

**Comment by YakudzaKY** [comment]
> Fixed in next release.

looks like frames now work like MODEL MOUSE OVER, but before downtrail it was UI MOUSEOVER.
Now works well with macro
Not work well with redirect plugin or similar plugins.

**Comment by zbee** [comment]
I was still in Automatic Mode when I tested. Great spot, Yakudza.
Can confirm, when I hover over a party member my current Redirect setups and other UI Mouseover setups do nothing, but if I change them to Model Mouseover then they work.

**Comment by Tischel** [comment]
Fixed in v2.2.0.1
