### ISSUE TITLE
[Bug]: Hononific no longer works with Delv UI in Dawntrail

### ISSUE THREAD

**Issue by AetherCollective** [DelvUI/DelvUI#1200]
### What are you trying to do?

See Honorific Titles in Delv UI

### What is the expected behavior?

Delv UI titles replaces with honorific 

### What actually happened?

Honorific titles are ignored

### Suggested solution

Please fix when possible 

### Logs

No logs

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
I'm trying to figure it out and also getting in touch with the Honorific plugin dev to solve this.

**Comment by Zeffuro** [comment]
I also looked into it and it has to do with the Ipc, Honorific may need to change what they submit or Dalamud has to provide a way so we can share IPlayerCharacters again

![image](https://github.com/user-attachments/assets/89c9b445-ee02-4b99-83a8-00ed53b40928)

**Comment by Tischel** [comment]
Fixed in v2.2.0.7

**Comment by AetherCollective** [comment]
Confirmed. Thanks!
