### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ohantuo** [DelvUI/DelvUI#1201]
### What are you trying to do?

Party UI doesnt show duty support/trust npc's as part of the team.

### What is the expected behavior?

Before DT update its was working fine, so i'm pretty sure this is just a bug. 

### What actually happened?

Missing frames.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.2.0.1
