### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Razoroth** [DelvUI/DelvUI#1202]
### What are you trying to do?

Change health and mana bar labels text from current to current-percentage or current-percentage-shortened

### What is the expected behavior?

Label text [mana:current-percentage] & [health:current-percentage] should show as a % and [mana:currrent-percentage-shortened] & [health:currrent-percentage-shortened] should also show as a %

### What actually happened?

Label text [mana:current-percentage] & [health:current-percentage] shows the same as [current] and [mana:currrent-percentage-short] & [health:currrent-percentage-short] shows the same as [current-short]

### Suggested solution

Correct label display to show as a percentage and not an absolute value

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.2.0.1
