### ISSUE TITLE
[Bug]: Nameplate player state icon shows job icon

### ISSUE THREAD

**Issue by Khelzor** [DelvUI/DelvUI#1204]
### What are you trying to do?

Display player state icons on nameplates for 'Other players'

### What is the expected behavior?

Should show the state icon like disconnected, watching a cutscene, afk, etc

### What actually happened?

Shows the job icon instead when theres no state icon to show, so now with job icons on as well other players have a job icon to the left and right of their nameplate
![ffxiv_dx11 2024-07-09 15-57-12](https://github.com/DelvUI/DelvUI/assets/19486188/50bd78f9-44c6-4409-a9b5-f3aa6f0fac83)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Khelzor** [comment]
Sorry, bad screenshot, this shows it
![Final Fantasy XIV  A Realm Reborn Screenshot 2024 07 09 - 15 59 51 99](https://github.com/DelvUI/DelvUI/assets/19486188/4cf57f9e-11e2-4cd1-a9c5-55193a5321e0)

**Comment by Narcasung** [comment]
I had the same issue, you just need to disable this setting

![image](https://github.com/DelvUI/DelvUI/assets/6689651/0b3ce13a-2dc5-4481-bf45-7648d982fa3d)

**Comment by Tischel** [comment]
You need to disable the job icons in the game nameplates and also this DelvUI feature conflicts with other plugins like PartyIcons.
