### ISSUE TITLE
[Suggestion]: Allow Vipersight gauge color to change based on buff

### ISSUE THREAD

**Issue by Blitzkind** [DelvUI/DelvUI#1207]
### What's your suggestion?

Currently the Vipersight gauge has two sections denoting the step of the combo you're in, and fills the gauge based on that colors you signify in settings. These colors (Default Blue and Red) do not have any bearing on what positional you need to fulfill.

I suggest that an option be added where the color of the final section or the glow that highlights the correct button be dependent on what buff you have. For example, if I have the buff that increases potency for rear positional finishers it'll fill the last section with one color, and if I have the buff for flank positional finisher it would be the other.

Currently the only way to know his at a glance is to look at the hotbar or buff bar. Worse yet, if you are Red-Green colorblind, it's even harder to know. Giving the ability for users to pick a color to signify this would be a great accessibility tool.

Edit: Screenshots to explain what I mean and what I want, hotbars modified to give info.

New Combo, no input
![image](https://github.com/DelvUI/DelvUI/assets/5423920/6171f42b-ee7b-43cd-ae7c-1b84295aa7ab)

Press Steel Fangs
![image](https://github.com/DelvUI/DelvUI/assets/5423920/93041ed1-47d3-483e-8843-f237ecdf0621)

Pressed Hunter's Sting
![image](https://github.com/DelvUI/DelvUI/assets/5423920/e41ca2d4-12ff-46f8-892d-0a33519e1dd9)

What I want here: Allow me to change the color of either the final section of the gauge or the glow to reflect that I need to do a flank positional as both options here are flank positional attacks. 

Likewise, I would like this to reflect the same for rear as I continue the combo as shown below

New combo, Rear buff
![image](https://github.com/DelvUI/DelvUI/assets/5423920/09957029-e8af-4b7a-b180-09d0e4e9aec9)

Second Step, Rear buff
![image](https://github.com/DelvUI/DelvUI/assets/5423920/fcfd5e67-0cdc-432b-bc75-0ba82ff4df89)

Press Swiftskin's Sting
![image](https://github.com/DelvUI/DelvUI/assets/5423920/1b4259fe-9356-4d76-bf61-57411dffa242)

What I want here: Allow me to change the final fill in color to be distinct from the first combo, such that I can know at a glance what positional I need to fulfill as both attacks here are rear positionals.

**Comment by cultbaus** [comment]
The vipersight gauge has a glow indicating which combo action will consume your currently active buff, if both sides are glowing that means that both finishers are valid.

**Comment by Alexcei47** [comment]
I had the same idea to implement, really good addin function to the bar

**Comment by Blitzkind** [comment]
> The vipersight gauge has a glow indicating which combo action will consume your currently active buff, if both sides are glowing that means that both finishers are valid.

That's not the issue here. The two second step parts of the combo will lead to either both flank positionals for the third step or both rear. The bar gives no indication of what positional you need to hit and requires you to either keep it memorized or look away from the vipersight bar/current mechanics to your hotbar which is not ideal.

**Comment by cultbaus** [comment]
> > The vipersight gauge has a glow indicating which combo action will consume your currently active buff, if both sides are glowing that means that both finishers are valid.
> 
> That's not the issue here. The two second step parts of the combo will lead to either both flank positionals for the third step or both rear. The bar gives no indication of what positional you need to hit and requires you to either keep it memorized or look away from the vipersight bar/current mechanics to your hotbar which is not ideal.

I think I see your point regarding early combo states, for the first execution of the combo chain or in instances in which you drop your buffs you will have either two flank or two rear depending on which 2nd part you use, but subsequent recasts can rely entirely on Vipersight.

**Comment by Blitzkind** [comment]
> I think I see your point regarding early combo states, for the first execution of the combo chain or in instances in which you drop your buffs you will have either two flank or two rear depending on which 2nd part you use, but subsequent recasts can rely entirely on Vipersight.

I'm not sure we understand each other completely as the vipersight bar can't be used at any point to know what positional you need to hit. I've updated my original post with screenshots to explain better. Sorry if I'm just misunderstanding what you mean :)

**Comment by Blitzkind** [comment]
Decided to be the change I wanted to see in the world and did it myself. Pending PR #1208 :)

**Comment by cultbaus** [comment]
> > I think I see your point regarding early combo states, for the first execution of the combo chain or in instances in which you drop your buffs you will have either two flank or two rear depending on which 2nd part you use, but subsequent recasts can rely entirely on Vipersight.
> 
> I'm not sure we understand each other completely as the vipersight bar can't be used at any point to know what positional you need to hit. I've updated my original post with screenshots to explain better. Sorry if I'm just misunderstanding what you mean :)

No you're absolutely right, this is my mistake, I don't know why I seemed to think this was the case previously

**Comment by Alexcei47** [comment]
At this point there is no sence in first combo bar color, it can also be pained with color of finishing positional)

**Comment by Blitzkind** [comment]
> At this point there is no sence in first combo bar color, it can also be pained with color of finishing positional)

So that's a little tricky. There exists a case where we are going for a specific finisher because we have the buff, we mess up the second button, and now have opposite positionals. We still want to hit the positional so we don't lean into a mistake even though we no longer have a buff.

In that scenario the safest way to color is based on what button you hit for step 2 (Hunter's sting or Swiftskin's sting), ignoring the buff altogether.

I didn't consider this until I started making the change. In theory, the first bar doesn't matter, and you could remove it all together but then you lose the notification on what button to hit.

**Comment by Zeffuro** [comment]
A lot of discussion here so first off, I made Vipersight bar to try and replicate what the official job gauge did. 
Now later we discover that it's sometimes off for the suggested buff (combostate 1 // Combo started) and that it might be a literal back and forth between the buffs. 

Now there's also the argument that not hitting what the game suggest for the buff is not detrimental to the game, it's actually better sometimes if you have the other buff almost fall off (since codewise we already directly check which of the 2 buffs need refreshing first.

```
if (swiftScaledDuration > huntersInstinctDuration)
                    {   // Glow left
                        glows = [false, true, false, false];
                    }
                    else if (huntersInstinctDuration > swiftScaledDuration)
                    {   // Glow right
                        glows = [false, false, true, false];
                    }
                    else
                    {   // Glow both
                        glows = [false, true, true, false];
                    }
```

I personally think that is the way to go but I do think the colors for the first part are kind of useless.
For the finisher, this is something to be discussed, we traditionally didn't have any rear/flank helpers and you can technically do this in DelvCD based on just the finisher buff.

I asked internally whether we want this or not.

**Comment by Blitzkind** [comment]
Oh, cool cool. Sorry if I overstepped with the change and posted too much here on it

**Comment by Zeffuro** [comment]
No problem, I just discussed it and I'll comment on it in the PR.
