### ISSUE TITLE
[Bug]: "Player state icon" is shown as "Job icon" in "Nameplates"

### ISSUE THREAD

**Issue by OuzenLapis** [DelvUI/DelvUI#1212]
### What are you trying to do?

Sprout, crown and other icons are not displayed - instead there is a job icon
![2024-07-11_17-08-15](https://github.com/DelvUI/DelvUI/assets/76729994/93003baf-e1ab-4ca4-9145-0a95e5363a87)

### What is the expected behavior?

"Player state icon" is shown as "Job icon" in "Nameplates" - always 

### What actually happened?

"Player state icon" is shown as "Job icon" in "Nameplates"

### Suggested solution

Please fix this

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Disable job icons in the game's nameplates.
Also disable PartyIcons plugin if you have it.
