### ISSUE TITLE
[Suggestion]: Missing CDs from Party Cooldowns

### ISSUE THREAD

**Issue by xMooni** [DelvUI/DelvUI#1214]
### What's your suggestion?

All new tanks 2mins are not yet in there (Upgraded versions of their previous 2mins) PLD - Guardian, WAR - Damnation, DRK - Shadowed Vigil, GNB - Great Nebula. Will need some kind of adjustment aswell so that both old and new shows up at the same time. WHM seems to be missing as a class from having Swiftcast tracked. SCH - Seraphism new big CD at level 100. SGE - Philosophia Lv. 100 skill. NIN - Dokumori which is the upgraded version of Mug obtained at level 66. Kunai's Bane upgraded Trick Attack obtained at level 92. 

Optional Suggestions to track:
SAM - Meikyo Shisui if possible since SAM has legit nothing tracked and would be nice to atleast have their burst skill there. MCH - Chain Saw and Barrel Stabilizer.

**Comment by xMooni** [comment]
Could we also possibly add so that we can grow Party Cooldowns on cooldownbar both down/up and left/right so for example: Down and Right and such like we have on buffs/debuffs. https://imgur.com/FSS6QDF

**Comment by kaedys** [comment]
While we're looking at upgrades and such, Warrior's Raw Intuition (ID `25751`), their initial defensive before they get Bloodwhetting (so levels 56 - 81), is not tracked, despite working very similarly to Bloodwhetting.  And the inverse, Gunbreaker Heart of Corundum (level 82+, ID `25758`) is not tracked (but Heart of Stone, their initial defensive, equivalent to Raw Intuition, is.

**Comment by Tischel** [comment]
Fixed in v2.2.0.10
