### ISSUE TITLE
[Bug]: Monk Masterful Blitz gauge shuffled

### ISSUE THREAD

**Issue by Asxa00** [DelvUI/DelvUI#1215]
### What are you trying to do?

This was an issue in the first build released for Dawntrail and got fixed, but seemingly reintroduced last update

![ffxiv_dx11_9lmVJMMmiJ](https://github.com/user-attachments/assets/7efed27e-10e9-4ae1-be9a-223584b2a24e)

### What is the expected behavior?

Blitz Chakra activates appropriately

### What actually happened?

Blitz Chakra has been shuffled again; Opo is activating Raptor, Raptor is activating Coeurl, and Coeurl activing Opo

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.2.0.4
