### ISSUE TITLE
[Bug]: Coil skills are treated as 3rd combo attacks for Vipersight gauge

### ISSUE THREAD

**Issue by Fateburn** [DelvUI/DelvUI#1221]
### What are you trying to do?

When using Hunter's Coil (flank)/Swiftskin's Coil (rear) the vipersight gauge gets updated as if that positional was used in the main combo.

For example, if my next 3rd hit needs to be a flank attack, but during the 1st or 2nd hit I use Dreadwinder and end with Hunter's Coil, the vipersight gauge will tell me to use a 2nd combo attack that leads to a rear positional 3rd attack.

If I've used the 1st attack and need to use a 2nd that leads to rear 3rd, if I then use Dreadwinder->Swiftskin's Coil it will tell me I need to use a flank leading 2nd. If I then use Hunter's Coil it goes back to telling me to use a rear leading 2nd.

It seems like the gauge is updated when the self buff is applied after using a Coil skill

Using Coil skills while on the 3rd attack does not update the gauge at all

The aoe versions Hunter's Den and Swiftskin's Den also update the gauge, with Swiftskin's Den suggesting a flank leading 2nd, and Hunter's Den suggesting a rear leading 2nd

### What is the expected behavior?

Coil/Den skills do not influence the vipersight main combo gauge

### What actually happened?

The opposite

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Zeffuro** [comment]
I've made some changes in my PR #1222 and I think it doesn't happen anymore but should probably be extensively tested.

**Comment by Tischel** [comment]
Fixed in v2.2.0.5
