### ISSUE TITLE
[Bug]: Starry Muse not being tracked correctly by Party Cooldowns

### ISSUE THREAD

**Issue by SlanDF** [DelvUI/DelvUI#1227]
### What are you trying to do?

Track Starry Muse in the Party Cooldowns

### What is the expected behavior?

Tracking Starry Muse should display when the party cooldown is currently up and when it goes on cooldown

### What actually happened?

nothing

### Suggested solution

Test this WITH a PCT and not being the PCT itself
I believe the same is happening with NIN party cooldown

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by SlanDF** [comment]
starry muse 3685 is what needs to be tracked

**Comment by Tischel** [comment]
Fixed in v2.2.0.10
