### ISSUE TITLE
[Bug]: 7.01 mnk gauge update

### ISSUE THREAD

**Issue by blessthequinn** [DelvUI/DelvUI#1228]
### What are you trying to do?

track fury stacks

### What is the expected behavior?

one stack for raptor, one for coeurl

### What actually happened?

two for raptor, three for coeurl

### Suggested solution

update removed some balls from mnk, gauge needs to be updated

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by blessthequinn** [comment]
it's supposed to be two for coeurl not one, mistyped

**Comment by Tischel** [comment]
Fixed in v2.2.0.5
