### ISSUE TITLE
[Bug]: Party frames drawn on top of character pane when multiple windows on top of them

### ISSUE THREAD

**Issue by claypnn96** [DelvUI/DelvUI#1242]
### What are you trying to do?

Noticed while reading equipment tooltips while character pane was dragged on top of my DelvUI party frames.

### What is the expected behavior?

Party frames should be drawn underneath windows that are on top of them at all times.

### What actually happened?

When the character pane is on top of DelvUI party frames, and another window (only works for some. Have observed with equipment tooltips, inventory, and duty finder) is also on top of the party frames, the party frames will display above the character pane. This appears to happen separately for each party frame element, as I've tried to demonstrate in the pictures. Name, class icon, etc only appear if the window is also touching their border, and are drawn underneath the party frame health bar if the window is touching both.

In the pictures below, I dragged my character pane on top of my party frames, then dragged my inventory pane on top of my character pane where my party frames are. As it touches each party frame element, they are drawn underneath the inventory but on top of the character pane.

![image](https://github.com/user-attachments/assets/c29b42ff-15da-472a-8bee-2e931eb4fee1)
Just the party frame health/mana bar displaying on top of character pane
![image](https://github.com/user-attachments/assets/1c33a16d-ab49-4147-ace3-8a53938fbec8)
Window touching icons and text as well, which are drawn below the health bar
![image](https://github.com/user-attachments/assets/9601f921-f166-4e44-9f87-957f4182edd1)
Touching just the icons and text

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by claypnn96** [comment]
Cool, thanks for the fast response. Apologies if it's been a frequent report

**Comment by Zeffuro** [comment]
Yep that's exactly what it is. 2 diff official game windows trying to clip the same window.
