### ISSUE TITLE
[Bug]: Ninja Suiton/Shadow Walker Bar not working

### ISSUE THREAD

**Issue by kijata** [DelvUI/DelvUI#1243]
### What are you trying to do?

The Suiton bar showing the duration of your suiton/Shadow walker buff is not working.

### What is the expected behavior?

The bar showing the duration of Shadow Walker.

### What actually happened?

no bar is showing up when casting suiton or huton

### Suggested solution

The suiton buff got replaced by Shadow Walker, so i guess the checked buff ID doesn't work anymore.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by gingertonik** [comment]
fixed in #1250

**Comment by Tischel** [comment]
Fixed in v2.2.0.8
