### ISSUE TITLE
[Bug]:  Dokumori not being tracked by cooldowns

### ISSUE THREAD

**Issue by SlanDF** [DelvUI/DelvUI#1244]
### What are you trying to do?

Track the upgraded mug on the cooldowns tracker

### What is the expected behavior?

for Dokumori to replace mug at lvl66

### What actually happened?

mug shows up and doesnt work
same probably happens with trick attack and kunais bane, will confirm once i get to 92

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by SlanDF** [comment]
confirmed that kunais bane the same happens

**Comment by gingertonik** [comment]
fixed in [#1247](https://github.com/DelvUI/DelvUI/pull/1247)
