### ISSUE TITLE
[Bug]: Mana Bar disappears when using Black Mage with Job Stone

### ISSUE THREAD

**Issue by U3b3** [DelvUI/DelvUI#1265]
### What are you trying to do?

Got to Lvl 30 and got my Job stone , if i'm equipping my Stone the Mana Bar disappears

### What is the expected behavior?

That the Mana Bar still shows up

### What actually happened?

Got to Lvl 30 and got my Job stone , if i'm equipping my Stone the Mana Bar disappears

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Zeffuro** [comment]
Black Mage has it's own unique manabar that you can change/move in Job Specific -> Magical -> Black Mage. In case you want the non specific manabar back you can enable the option "Use Generic Mana" or something like that over there.

**Comment by U3b3** [comment]
Thank you so much <3
