### ISSUE TITLE
[Bug]: don't work mouse binds on party frames

### ISSUE THREAD

**Issue by ErickShnaider** [DelvUI/DelvUI#1266]
### What are you trying to do?

I have enabled setting "mouseover" and use skill "Physick" by hovering over a party member's name in the party list and skill "Physick" is applied to that party member. I try to repeat the same with skill "Adloquium", but nothing happens, the skill does not work.

### What is the expected behavior?

I expected everything to work

### What actually happened?

I have the Physick skill bound to a keyboard key, and the Adloquium skill bound to a mouse key. This is not only true for scholar skills, but for all classes as well. Something is obviously blocking the skills assigned to mouse buttons from being used when the mouse is over delvUI elements.

### Suggested solution

I think we need to fix the issue that blocks the use of skills assigned to mouse buttons if the mouse pointer is hovering over delvUI interface elements

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Zeffuro** [comment]
There has been an update some time ago that made the mouse buttons processing more stable but you can reenable the old behavour by typing "/delvui mouse on" in your chat and you should be able to use your other mouse buttons as well

**Comment by ErickShnaider** [comment]
> "/delvui mouse on" in your chat and you should be able to use your other mouse buttons as well

I confirm. This solution helped. Thank you
