### ISSUE TITLE
[Bug]: Viewing Cutscene on Party Frames

### ISSUE THREAD

**Issue by grusomhet** [DelvUI/DelvUI#1270]
### What are you trying to do?

I enter a dungeon/ raid but _[Viewing cutscene]_ text bugs out. Witnessed this on NR, Alliance and on dungeon groups so far.

### What is the expected behavior?

The people watching their CS have _[Viewing cutscene]_ and people who don't watch any don't have the text.

### What actually happened?

I wasn't watching the cutscene and I got the _[Viewing cutscene]_ text, and my healer who was watching cutscene didn't have _[Viewing cutscene]_. I've seen this also happening with other, random people. Some people got the text when they don't watch anything, and people who do watch might not have any text about them viewing the CS, it seems a bit random.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Atroskelis** [comment]
I can confirm and provide proof of this
![image](https://github.com/user-attachments/assets/b876c5c2-d1d5-409d-a8e7-a77b231ba0be)

It happened :

1. at start of dungeon
2. during final boss battle

**Comment by Tischel** [comment]
Fixed in v2.3.1.6
