### ISSUE TITLE
[Bug]: Party Frames disappear

### ISSUE THREAD

**Issue by grusomhet** [DelvUI/DelvUI#1271]
### What are you trying to do?

On two different MSQ roulette dungeons I have opened DelvUI settings, and my party frames did disappear as a result.

### What is the expected behavior?

Party Frames stay visible unless disabled manually

### What actually happened?

I opened settings due other bug, closed the settings and my party frames were just gone. They don't reappear even when I try to disable and enable party frames, or change the profile. Only leaving the dungeon resets the UI it seems, and I can see them normally on a next dungeon/ instance I queued.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.3.1.6
