### ISSUE TITLE
[Bug]: Duplicate Party Members

### ISSUE THREAD

**Issue by Axiarus** [DelvUI/DelvUI#1272]
### What are you trying to do?

Show party members.

### What is the expected behavior?

To show the different party members in the party frames while entering a dungeon.

### What actually happened?

Joined a party. Party frames were correct. Entered the new dungeon and the party frames showed one player and three duplicates of another. Clicking either of the duplicates targeted the duplicated player and made the other duplicates on the party frames see through. This happened again when I left the dungeon.

### Suggested solution

Logging out and back in fixed the issue. Toggling preview in the DelvUI settings also fixed this problem.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.3.1.6
