### ISSUE TITLE
[Bug]: Duplicates the same player name.

### ISSUE THREAD

**Issue by NathanCaelum** [DelvUI/DelvUI#1273]
### What are you trying to do?

I was doing hunt trains like normal, never had issues before.

### What is the expected behavior?

There should be 7 unique players and when clicking on each player it should target the right player. It should not show me as the party leader if I join a group.

### What actually happened?

When I joined an almost full party I didn't noticed it at first but after a while I noticed that the same player got duplicated 6 times and when I clicked each of the frames with the same name it would always target the same player no matter which one I clicked rather than targeting the actual player who should have been there. Screenshot shows 6 of the same character name. Upon joining it bugged and shows me as the party leader despite joining someone elses group.
![Screenshot 2024-11-22 103938](https://github.com/user-attachments/assets/26f8cf41-80d0-4d1d-876e-1e7dbdc2d12f)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.3.1.6
