### ISSUE TITLE
[Bug]: Party frames sorting doesn't match in-game Social tab since 7.11

### ISSUE THREAD

**Issue by bayta-88** [DelvUI/DelvUI#1274]
### What are you trying to do?

Enter any instance and have my party frames sorted.

### What is the expected behavior?

Party frames should be sorted in the same order as they appear under the "social" tab. 

### What actually happened?

The party frames appear sorted in an apparently random order.
For instance: In a dungeon I was the tank and my DelvUI party frames appeared sorted in the order: Tank, DPS (Summoner), Healer, DPS.
In 8-man instances the order also appears to be semi-random, not even having all the people of the same role together. For example as a DPS I got this order in a trial: Healer, Tank, DPS, Healer, 3 DPS, Tank.
In both instances if I open the "Social" tab in the game the order doesn't match the one of the DelvUI frames (they are properly sorted by role instead).
Screenshot attached with names removed (I am the RPR).
![y](https://github.com/user-attachments/assets/b5a2f7a4-9260-4773-9e04-5008e39942b1)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v2.3.1.7
