### ISSUE TITLE
[Help wanted]: Cannot Use Mouse Buttons M4 or M5 For Mouse Over Actions On Party Frames

### ISSUE THREAD

**Issue by DeviousIntents** [DelvUI/DelvUI#1277]
### What's the issue?

Hello! I have been using DelvUI for a long time now and I love it! There is one thing that has bugged me for years though. When I try to use M4 and M5 mouse buttons for mouse overs on the party frames, it does nothing. If I use the same mouse overs on the built in ff14 party frames, it works fine. 

Am I missing a setting, or is this a bug? 

Any information would be greatly appreciated. Thank you!

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Zeffuro** [comment]
You need to use `/delvui mouse on` once to enable special mouse binds (this used to be the default but because it was causing problems in certain situations it's not on by default anymore).
