### ISSUE TITLE
[Suggestion]: Avatar Picture

### ISSUE THREAD

**Issue by Dajova** [DelvUI/DelvUI#149]
### What's your suggestion?

So i just wonder if it would be possible (in the future) to be able to set a avatar picture to the frames (at least player and target) and/or overlay (kinda like how you can in ElvUI).
Would be kinda cool to have (if its even possible). Kinda like this (how i have in WoW):
![image](https://i.imgur.com/SdOC03L.png)

**Comment by jdsmith2816** [comment]
This is something that, if it were to ever happen, would be so far into the future as to have no value to keep around as a feature request for now.   If I were you I'd make a plugin request on the ffxivlauncher discord asking for a way to show the party frame render of the character in a seperate window or something.  If someone figures out how to do that then we could figure out how to attach it to our UI.  Until then.... no go.
