### ISSUE TITLE
[Suggestion]: WHM preview video

### ISSUE THREAD

**Issue by katyfromgithub** [DelvUI/DelvUI#168]
### What's your suggestion?

hello since i dont know how to add to the wiki here is a link to a video that shows the ingame whm layout for whm i hope my setup is good enough

https://www.youtube.com/watch?v=uJhCLk4_TG4

**Comment by Kanubiz** [comment]
hey! thank you for the submission but we only use the default preset for the bars in the wiki, we already have one ready, just havent updated it yet!
