### ISSUE TITLE
[Suggestion]: Configurability suggestions

### ISSUE THREAD

**Issue by sadtaco** [DelvUI/DelvUI#2]
### What's your suggestion?

**General**:
- Alpha options for all colors, with `0` alpha being a concise way to just make things invisible, including bars.
This way one could feasibly make the health bar transparent, with no background, and just have an outline and number if they want.
Of course it'd be nice if, intentionally, render steps are entirely skipped if `alpha == 0`
- Ability to `Add color change trigger` to append to a list of conditions and triggers. ie `if value <= 30%, change background color to ...`
For as many things as possible. Just background color would be nice to start, but being able to do it for fonts, outlines, and so on is also nice.
- Type presets. ie be able to configure the font size, spacing, outline for it, so on that you want up top then for all the font options have a "use preset" dropdown to select your preset as a starting point which can then be overwritten without that option itself.
Same for bars, might generally have a size, outline, and glow and such you want consistent for all your bars, then in the bar configuration yourself you are overwriting just the colors.
- Z-sorting. I could potentially put my mana skills *within* the mana bar, and spender skills *within* the resource bar, if I wanted to with this. Though transparency can also enable this sort of config in a way.
- Use vanilla FFXIV HUD Layout by default, and offset on top of that.
Not sure if this is done already. It looked like it wasn't, though and that screen x/y was used.
These are easy to drag and move around, include a snap grid, and so on.
If the UI mod is done well and includes all the functionality of the vanilla elements but is simply configurable, then we won't need those default elements.
Notably, this is a problem with ZeffUI where you can't just disable the parameter bar to use its health and mana bars because that one doesn't work for DoH jobs.
- On/off configuration per element.

**Bars**:
- Configurable color to the bar behind the scaling background bar
- 2 and 3 stage gradient fills and gradient angle.
- Inside & Outside Glow (100% spread to use as outline instead).  Option for whether these wrap the parent bar, or if depleting the bar's resource 
Not sure how to write that option concisely, but hopefully this makes sense. A more visual example to think of is what if I wanted to have my mana bar be transparent, and be a glowing outline around my hotbar.  When mana goes down below 100%, instead of the right side of the outline/glow sliding into the icons I'd want the coloring removed there entirely and it instead just be bar depleting along the lines above and below it.
- Corner rounding
Percentage rounding would also be nice, like some people might want RDM bars to be circles so they could just simply corners to 50%.
- x/y Size
- x/y Offset
- Rotation
Could simply flip 180 to make bars deplete from left-to-right instead which would also accommodate those wanting vertical health/mana/job bars.

**Fonts**:
- Glow
- Font Face
- Letter Spacing
- Letter Size. Including % usable for size when you are loading a preset (ie preset could have font size as 20, but his element you might want 60% the usual font size used)
- Force Capitalization on/off

**Mana Bar**:
- Block step configuration for `500/1000/2000/3000` mana. Per job configuration for steps, as for example 500 or 1000 step is most useful to healers. DRK just needs 3000. PLD just needs 2000.
Lots of games have this so you can easily see at a glance how much health or mana something has. Example (on health): https://i.imgur.com/gpzxxLX.jpg?fb
Would be nice if these lines can be positioned up/down and also scaled up/down so it can be changed to a notch instead.

**Target Bar Health**:
- Configurable colored line for `Limit Break` points at `MLB1, MLB2, MLB3, RLB1, RLB2, RLB3`, similar to block steps for mana bar **for enemies**.
Also would be nice if these lines can be positioned up/down and also scaled up/down.
- Configurable colored line for `# potency` and `# potency crit` configuration when targeting a party member. ie, could set it to 600 for Lustrate. This should ideally be per-job configurable and hideable for jobs that don't have targetable heals.
- ! Offset for target position. Personally think I'd nest mine inside

**Enemy Cast Bar**:
- Potentially make it so it's the outline color or font color that's configured for if the cast is interruptible? If you're going to change the bar color itself for phys/magic or other configuration since stunnable is its own separate thing on top of that.
- I don't care much about phys/magic and would instead like configuration to highlight whether it's a mechanic wipe, tank buster, vuln stacker, etc... but I realize that'd require compiling a list of every ability in the game to check against. To at least have this functionality and have a `JSON` or simple new line ordered list we can start filling ourselves as we go. Would be especially nice if there's a kind of notepad editor that can be opened in Dalamund settings, but I'm not sure there is, where if we see a spell is something in a fight we could go in and add like `"mechanic wipes: [ "ancient flare" ]` or whatever.

**Comment by jdsmith2816** [comment]
Thanks for this;  there's some really valuable feedback here!

**Comment by sadtaco** [comment]
Another suggestion to add that's come to bug me with 2.0:

Rework misc colors to include: 
 * Color presets (like you have with fonts to add then select with a dropdown, that is great)
 * Role color config (Tank, melee dps, phys dps, caster, healer, barrier healer)
Replace `Use Job Color` tick box with `Use Color Preset` and the drop down of which color to use.
Extend this to be selectable for `fill bar color`, `bar background color`, `gradient color`, `text color`, `border color` and `outline color`, so job, role, or any color presets can be used here.
I'd also like to be able to open up a small box to modify the color preset everywhere within where the preset is selected. Same for fonts. Should probably warn that this will affect all instances of the preset when that's done. :)

Combining some of these, I'd like to be able to set my target and/or target-of-target bar gradient color to .
These job colors actually REALLY confuse me, personally. I'd probably do something like... Have the target-of-target (and party frame) bars be role color, and just have job color be a light gradient over that and/or maybe the name or border outline be job color.
I actually frankly like job icons and would prefer to just show those, most likely. Us who have played FFXIV a while are more used to those I think.

I would also like to see it possible to "copy paste" similar to presets for each group of settings.
Like `Cast Time` and `Cast Name` are roughly the same options, and buttons to copy/paste in the corner of their config group would be nice.  If a config group doesn't have the same options, it should just ignore the lines it doesn't have when pasted in.
