### ISSUE TITLE
[Suggestion]: Compiled List of suggestions from first viewing of current Job UI's

### ISSUE THREAD

**Issue by KalenDragonsong** [DelvUI/DelvUI#226]
### What's your suggestion?

In the BLM and RDM ui's the proc timers are parented in a way that change either the polyglot or Dual cast ui elements will resize the proc bars, deleting them essentially if made too wide.

Summoner could really use an Egi Assault action indicator above/below the Ruin IV indicator. Ideally showing both availability and cooldown. Since Egi-Assaults both Directly effect Ruin IV and are also strong movement attacks on their own this is a really important piece of info to have available.
Also a meter that shows the durations of Dreadwyrm Trance, Demi-Bahamut, and Phoenix Trance would be really nice especially alongside and indicator for Akh-Morn/Revelation that also maybe lights up for trance availability? or perhaps the duration bar has a darker shaded bar that shows the cooldown of Dreadwyrm and Phoenix trances respectively.

With MCH a thin indicator for Gauss and Ricochet charges would be handy considering it ties in with the Heat Blast mechanic. 

Maybe having a way to flip certain indicators such as the shinpu/jinpu buff durations so its Jinpu/Shinpu as an option for people like me who have the muscle memory of the Jinpu combo further left of the shinpu one. Its minor but it'd be a nice lil QoL.

For Dragoon maybe a jump ready indicator in between the two eyes of the dragon indicators? Idk this ones a tiny qol but it would look nice? XD. Also none of the bars have borders for DRG except for the Eye indicators but im sure you know that already.

I feel like tanks and healers should have Defensive and Healing specific orientated bars in place. 
Ast is a really good example of this. but it could still be expanded with a neutral sect duration as well as cd's for some big ogcd heals like celestial opposition and essential dignity. 
With Whm you could have assize, benediction/divine benison, and temperance(wings), maybe a duration window for asylum.
For Sch both fairy ogcd heals, Excog, recitation and dissipation would all be really important ones as well. And definitely seraph and its consolation charges too. also sacred soil duration as similar to asylum. 

For tanks its a bit harder but i'd definitely start with the signature skills, heart of stone, TBN, Sheltron and Nascent flash/raw Intuition. and then maybe also some of their bigger cooldown durations and invuln durations. A dual bar setup similar to the BLM proc bars for fire and thunder procs could be used to display their 30% cooldown(shadow wall, Vengeance) alongside rampart. 

These are just some initial observations before even playing but I hope you find them useful and there's at least a few things here that strike as being worth the effort to implement.

**Comment by ryrael** [comment]
Thought I'd piggy back off this suggestion - I really agree with trance & demi summon duration indicator
**Both of these things are pretty important information.** 
DWT duration is pretty important to see what weave space is available, how long you have instant casts & when your last GCD to deathflare is coming up
Demi summon duration is pretty important to allow correct demi summon rotations, moreso for bahamut so you have a visual indicator for the last 2 instant cast GCDs to get the most wyrmwaves.

Thanks :>
