### ISSUE TITLE
Dark Knight Blood Gauge partial fill color visibility

### ISSUE THREAD

**Issue by poly1k** [DelvUI/DelvUI#250]
Dark Knight Blood Gauge segments are difficult to see when not full.
Misconfigured to use bar backdrop instead of a more visible partial fill color.

Create config option and color in MiscColorMap for general job bar use.

![ffxiv_dx11_jjvK4MFsag](https://user-images.githubusercontent.com/89595918/132102721-d1e6dbc8-25be-4a8a-92ac-d0838e753d73.png)

**Comment by jdsmith2816** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dark Knight Blood Gauge partial fill color visibility](https://trello.com/c/c80lMNPj/46-dark-knight-blood-gauge-partial-fill-color-visibility)

**Comment by poly1k** [comment]
Fixed in #251
