### ISSUE TITLE
[Suggestion]: Layout Editor

### ISSUE THREAD

**Issue by MazeXP** [DelvUI/DelvUI#278]
### What's your suggestion?

Editing of the UI using a layout editor would be a neat feature.

Some prototype for a layout editor by me:
https://p.mazexd.me/file/gl8alHqwCC0nnaEx/88GcXKZoSdioTuLe/9Z25wI4wZk.mp4

**Comment by MazeXP** [comment]
Any feedback?

**Comment by Tischel** [comment]
This is already in the works

**Comment by MazeXP** [comment]
Ah okay, did not see any branch with a layout editor.
Thought the layout editor, visible in the video might be useful as a starting point.

**Comment by Tischel** [comment]
Added in beta2
