### ISSUE TITLE
[Bug]: Text font and Ast plugin crash on specifically my alt.

### ISSUE THREAD

**Issue by KorraVarnas** [DelvUI/DelvUI#353]
### What are you trying to do?

Play using Delvui On my alt.

### What is the expected behavior?

the UI should work like it does on my main.

### What actually happened?

DelvUI stops using the correct font in the names and texts and when switch to certain classes (ast) it just crash with a notice to contact the plugin devs. This only occurs on my alt and does it regardless of the plugin settings file which is perplexing to me.

Main: Korra Varnas
Alt: K'orra Quah (the malfunctioning one.)

Add both characters names just in case that's relevant to bug.

### Logs

```shell
XLLOG Output: https://i.imgur.com/SDMUVRx.png
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by nilaykumar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AST crash](https://trello.com/c/1cbWry3w/108-ast-crash)

**Comment by KorraVarnas** [comment]
Turned out to be a weird interaction with PingPlugin. Just documenting for anyone who reads this.
