### ISSUE TITLE
[Suggestion]: Text offset for castbar

### ISSUE THREAD

**Issue by shiokoufu** [DelvUI/DelvUI#354]
### What's your suggestion?

Much as the title says, having text offset for the castbar would allow for some different looks to keep consistent with the unitframes like this for example.

![image](https://user-images.githubusercontent.com/90427259/132774805-97aace28-4d46-47f6-a9d3-43ae4142cd08.png)

I personally prefer thin bars with text outside them and I do the same with my castbar as well (given that I'm working on making my UI look similar to how I have in WoW as much as I can).

**Comment by Tischel** [comment]
This will be possible in the next beta.
