### ISSUE TITLE
[Suggestion]: NIN Huton gauge ideas

### ISSUE THREAD

**Issue by shiokoufu** [DelvUI/DelvUI#358]
### What's your suggestion?

Would be nice to have an option to hide text on the Huton gauge and to instead have the color of the bar change when its duration is below 40s. Me ape, me like color and not number.

**Comment by nilaykumar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Small improvements on NIN bar](https://trello.com/c/ctat6a4a/111-small-improvements-on-nin-bar)
