### ISSUE TITLE
[Bug]: Primary resource text offset not working

### ISSUE THREAD

**Issue by shiokoufu** [DelvUI/DelvUI#359]
### What are you trying to do?

Doesn't seem as though the text offset option for the primary resource bar is working at all. Changing both X and Y offset changes nothing for the text on screen.

### What is the expected behavior?

Text moves on X and Y when offset is changed.

### What actually happened?

![image](https://user-images.githubusercontent.com/90427259/132782619-119b15d3-beeb-4a92-a8a8-984408dac912.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by h4cky** [comment]
Thank you for the report!

**Comment by h4cky** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add primary resource bar text offset](https://trello.com/c/G3P8tPaH/115-add-primary-resource-bar-text-offset)
