### ISSUE TITLE
[Suggestion]: Text tag for first/last name only

### ISSUE THREAD

**Issue by SkorPlays** [DelvUI/DelvUI#360]
### What's your suggestion?

Would be nice to have the option to only display the firstname or lastname. 
like [name:first] and [name:last]

**Comment by pascbeck** [comment]
already has been implemented on beta3
![image](https://user-images.githubusercontent.com/55634271/134936527-cde9727f-7ae4-4ea7-9cb6-aa6611764b9f.png)
