### ISSUE TITLE
Config bug

### ISSUE THREAD

**Issue by yakiro-nvg** [DelvUI/DelvUI#364]
https://github.com/DelvUI/DelvUI/blob/e608e183ac10f9af779efb68ffbf0adf26a0f1fd/DelvUI/Interface/StatusEffects/StatusEffectsListConfig.cs#L94

It should be:
```csharp
changed |= IconConfig.Draw();
```

**Comment by nilaykumar** [comment]
Changed in the upcoming refactor #375, can be closed.
