### ISSUE TITLE
Ninja Mudra display tweaks

### ISSUE THREAD

**Issue by Sservis** [DelvUI/DelvUI#365]
First, great work, I look forward to losing a chunk of playing time today tweaking things :slight_smile:
Copied from Discord #feedback

Everything below was mostly written with a brief look at the Ninja Mudra bar, but the ideas in 1, 2, and 4 likely apply broadly across the various profiles.

1) Default or an option to show time remaining on the charge, not how charged up it is so far.  The 4 in the screenshot should be 16 or so (subsecond rounding/timing, might be 15 or 17 too.  Time to ready seems much more important than time charging so far.

2) An option to not show a number when it's full, so the 20 in the screenshot should not appear at all.  Bar is full, I don't need/want more information.  (and based on #1 it would be 0 not 20 as it's 0 seconds to ready)

3) Ninja specific, With "Show Ninjutsu Text"=off the bar shouldn't change when I activate Mudras.  I'd like the timers to remain present/visible rather than it changing to a plain bar.

4) I know you have a lower priority item for adding positioning/sizing elements to all the items.  So font size and bar size is coming already.  I want the numbers to fit inside the bar, probably slightly smaller #s and slightly thicker bar.  Stating this for completeness.

**Comment by nilaykumar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Small improvements on NIN bar](https://trello.com/c/ctat6a4a/111-small-improvements-on-nin-bar)
