### ISSUE TITLE
[Suggestion]: Standardize manabar text options

### ISSUE THREAD

**Issue by Sservis** [DelvUI/DelvUI#366]
### What's your suggestion?

I'm sure this already is on a work list, but here's a checklist item, along with standardizing all common items once the profiles reach stability themselves.

White Mage relies on the global option to "Show Primary Resource Value"
Black Mage and Paladin have class specific options.
(did not compile more)

In addition Paladin displays the full value as 10.0K whereas Black Mage and White Mage show 10000   Personally I'd love an option to never see the last two digits.  so 0 - 99 (or 100, but hiding the number when full would be even more awesome)

**Comment by vond82** [comment]
#683
