### ISSUE TITLE
[Suggestion]: Focus and Target of Target frame improvements

### ISSUE THREAD

**Issue by Sservis** [DelvUI/DelvUI#370]
### What's your suggestion?

Match frame expectations to how they work in FF's UI (or better)

Right click on Target works to popup the context menu, however it does not on focus and it does in FF's UI

Also cannot click on the Focus frame to target it.  This also works in base UI.

Note: Base UI doesn't have a context menu for target of target, but if possible could be awesome..  When I right click in base UI on target of target it swaps my target instead of giving me an menu.

**Comment by Laxxzz** [comment]
Currently we only have submenu working on target frame however eventually all base ui submenu functionality will be ported to DelvUI.

**Comment by Tischel** [comment]
Added
