### ISSUE TITLE
[Suggestion]: Sound Notifications

### ISSUE THREAD

**Issue by Amasoful** [DelvUI/DelvUI#373]
### What's your suggestion?

When using Simple Tweaks to hide the Job Gauges, also the sound notifications related to them are removed (Eg: when resource is enough to cast a spell like Shoha and full kenki gauge for SAM or DRK spells) for some reason, which segways nicely into my suggestion.
If it is possible for DelvUI to have native Job Gauge removal that can remedy that issue of removing sound notifications instead of using Simple Tweaks that would be great!
Moreover, Is it possible to add sound notifications on user defined thresholds for different resource/buff/debuff bars, same as the sound effects used in the Dalamud Plugin Job Bars, For example, when Buff/Debuff that you must maintain is below 5s. then a sound notification pops up to remind you to refresh it! also those sound notifications to be defined by users from the existing sound effects in game eg. <se.01> etc.

**Comment by Laxxzz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Base UI job gauge toggle (keep sounds)](https://trello.com/c/dhvNzqvQ/137-base-ui-job-gauge-toggle-keep-sounds)

**Comment by Laxxzz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sound notifications for resource/buff triggers (Job Bars sounds)](https://trello.com/c/sfIm1Nin/138-sound-notifications-for-resource-buff-triggers-job-bars-sounds)
