### ISSUE TITLE
[Suggestion]: A 0.5 second indicator on the GCD timer bar

### ISSUE THREAD

**Issue by Clickeddaisy** [DelvUI/DelvUI#377]
### What's your suggestion?

Like the title suggests, On the GCD timer bar i would like an option where the last 0.5 seconds to have an indicator so you know exactly when you can queue up your next GCD ability or change the colour of the whole bar when it has 0.5 seconds and less left.

And just as a side request for the GCD timer instead of it going away when it is finished have it as full instead of empty when it finishes.

Love the Plugin BTW keep up the good work :)

**Comment by Laxxzz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add indicator on GCD bar To Show When You can que Next Ability](https://trello.com/c/lo3Y4nHd/139-add-indicator-on-gcd-bar-to-show-when-you-can-que-next-ability)

**Comment by Tischel** [comment]
> And just as a side request for the GCD timer instead of it going away when it is finished have it as full instead of empty when it finishes.

This is already possible with the "Always Show" setting.

**Comment by Clickeddaisy** [comment]
> 
> 
> > And just as a side request for the GCD timer instead of it going away when it is finished have it as full instead of empty when it finishes.
> 
> This is already possible with the "Always Show" setting.

Sort of. It will always show the background. What i want is when the bar fills it stays filled instead of going away.
