### ISSUE TITLE
[Suggestion]: Better Class Color adjustments

### ISSUE THREAD

**Issue by Sservis** [DelvUI/DelvUI#418]
### What's your suggestion?

Organize all the class color options so they can be tweaked in sync.  Checking if say Dragoon and Black Mage are too close means juggling tabs in the config and not seeing how close or not they are side by side.  I'm sure this is exacerbated by my partial color blindness and Dalmud not going through the accessibility filters in game I have applied to all FF UI to assist me.

A single class color tab where all items are available to set seems simplest.  Alternatively, an option to display example bars side by side for all jobs to visually see the differences would work.  Both is probably better.

**Comment by Laxxzz** [comment]
There is a seperate color tab including specifically what you've requested here, being added to a coming beta build :)
