### ISSUE TITLE
[Bug][Beta2]: Hide default job gauges (after commit #439)

### ISSUE THREAD

**Issue by fitqt** [DelvUI/DelvUI#444]
### What are you trying to do?

Trying to use "Hide Default Job Gauges" together with suboption "Disable Job Gauge Sound".

### What is the expected behavior?

Job gauges and/or sounds are hidden/muted in all cases.

### What actually happened?

When just using main option "Hide Default Job Gauges", gauges and job messages when you unlock them, e.g. Paladin "Oath Gauge expanded!" are hidden and it does persist through zoning/cutscenes albeit there is a second delay between them disappearing each time. 
Currently tested cases where they dont disappear are:
1. Entering dungeon through Duty Finder
2. After the end boss cutscene

When enabling suboption "Disable Job Gauge Sound", gauges and job messages persist through teleporting/zoning, entering dungeon and end boss cutscene. Case when gauge gets hidden (job message persists) is when you open dialog with a NPC, but as soon you end it, the gauge shows again. Haven't tested actual sound muting.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by h4cky** [comment]
interesting..
Thanks!

**Comment by Laxxzz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hide default job gauges functions not consistent in all cases](https://trello.com/c/QnCRfBe0/173-hide-default-job-gauges-functions-not-consistent-in-all-cases)
