### ISSUE TITLE
[Suggestion]: Hide and Tank Stances

### ISSUE THREAD

**Issue by rukk1** [DelvUI/DelvUI#498]
### What's your suggestion?

Would love the option to customize the hide features a bit more, specifically showing target while hiding everything else.
Also would love more options to customize the tank stance indicator.  My player bar is drastically different shape than the default and the tank stance indicator doesn't fit well.

New update is pog can't wait for party frames.  Thanks.

**Comment by vond82** [comment]
We have a ticket to make the tankstance indicator more customizable, just not something that was prioritized for beta2. So soonTM :)

[https://trello.com/c/YAi5wavM](url)

**Comment by rukk1** [comment]
Awesome, thanks.

One more wishlist item that I forgot to ask for is if it's possible to extend the zone based hide rules.  For example having the hide rules be hidden in dungeons/raids, so you can see cooldowns between pulls.
