### ISSUE TITLE
[Bug]: Partyframes MP bar does not show GP/CP (DoL/DoH resource)

### ISSUE THREAD

**Issue by sadtaco** [DelvUI/DelvUI#670]
### What are you trying to do?

Remove my resource bar since I can see it on partyframes and shouldn't need it duplicated in two places on my UI.
This is the default behavior of party list, to show GP for DoL and CP for DoH jobs instead of MP.

### What is the expected behavior?

When someone is a Crafter/Gatherer, it should show their resource in place of Mana when `show only healers` is unchecked.

### What actually happened?

The resource bar is empty and shows 0 for Gatherer and Crafter resource on Partyframes.

### Suggested solution

`[mana]` type tags should always roll over to the next applicable resource to track when the given job has no mana.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
Fixed in v0.3.1.0
