### ISSUE TITLE
[Bug]: Game crashes when switching characters

### ISSUE THREAD

**Issue by zotlann** [DelvUI/DelvUI#686]
### What are you trying to do?

Switch characters.

### What is the expected behavior?

When I log out from one character and login to another character, I expect the game to load.

### What actually happened?

The game crashes after the loading screen finishes.

### Logs

```shell
[ERR] [DelvUI] ERROR getting party data: Exception of type 'System.OutOfMemoryException' was thrown.

This is reproducible for me with the following steps.
Launch the game through xivlauncher.
Login to a character.
Join a party.
Leave the party.
Logout of that character.
Login to a different character.

The game crashes after the loading screen with the above error message spammed in dalamud.log
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Should be fixed in https://github.com/DelvUI/DelvUI/pull/698
