### ISSUE TITLE
[Bug]: Non-Latin player name shown as gibberish when in a cross-world party.

### ISSUE THREAD

**Issue by 4679** [DelvUI/DelvUI#688]
### What are you trying to do?

Non-Latin player name shown as gibberish when in a cross-world party on Chinese client, but in a normal party it's working as intended.
![Snipaste_2021-10-15_11-01-31](https://raw.githubusercontent.com/4679/cuddly-broccoli/master/picgo/Snipaste_2021-10-15_11-01-31.m6k4ofow5r4.png)

### What is the expected behavior?

Non-Latin player name shown normally when in a cross-world party

### What actually happened?

Non-Latin player name shown as gibberish when in a cross-world party

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by 4679** [comment]
It should be "星空琉璃", "苏沐影" and "丽若思".

**Comment by Kanubiz** [comment]
oh so all hanzi are wrong

**Comment by Kanubiz** [comment]
i thought it was only the ones with ?
we'll look into it, thank you!

**Comment by Kanubiz** [comment]
yeah i meant i thought only the hanzi with "?" were missing and the rest of the name was good :)

**Comment by Zeffuro** [comment]
I think you're right.
Reading through the code at the moment:

```
        private string? NameForIndex(int index)
        {
            if (HudAgent == IntPtr.Zero || index < 0 || index > 7)
            {
                return null;
            }

            IntPtr namePtr = (HudAgent + (PartyCrossWorldNameOffset + PartyCrossWorldEntrySize * index));
            return Marshal.PtrToStringAnsi(namePtr);
        }
```

`Marshal.PtrToStringAnsi(namePtr)` probably needs to be different depending on what encoding the name has. I don't know if changing it to something like PtrToStringUni or PtrToStringUTF8 will work for this.

![rider64_2021-10-15_09-57-51](https://user-images.githubusercontent.com/4972345/137452752-6ad7c7eb-e1b3-4430-b919-57d5e06eb43f.png)

I don't have access to the CN client or have any friends with characters written in Hanzi so this would have to be tested over there.
