### ISSUE TITLE
[Bug]: Stacks on uncropped icons

### ISSUE THREAD

**Issue by coffeepee** [DelvUI/DelvUI#700]
### What are you trying to do?

Show correct number of stacks on buffs and debuffs when using uncropped icons

### What is the expected behavior?

Stacks increasing/decreasing with uncropped icons

### What actually happened?

Uncropped icons always show 1 stack regardless of how many you have
![delvuibeta3buffdebuffstacks](https://user-images.githubusercontent.com/92605359/137548302-529d7564-b089-400c-b2a8-29330c89aac3.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in https://github.com/DelvUI/DelvUI/pull/701
