### ISSUE TITLE
[Bug]: Mouse cursor behind windows

### ISSUE THREAD

**Issue by SURFACIEN** [DelvUI/DelvUI#745]
### What are you trying to do?

When **DelvUI is active** my mouse **cursor** is **behind** all **windows** of dalamud.
If then i **turn off DelvUI** it stays the same.

![DelvUI-Mouse bug-001](https://user-images.githubusercontent.com/92701420/137661517-18e9a411-d768-4181-b83b-91745c41a3a0.gif)

**FF** must also be **restarted** so that the mouse **cursor** returns to its normal behavior while being **visible in front of the windows.**

![DelvUI-Mouse bug-002](https://user-images.githubusercontent.com/92701420/137662090-4a2c2986-57b2-417a-8ac6-0165b27f5906.gif)

### What is the expected behavior?

mouse **cursor**  being **visible in front of the windows.**

### What actually happened?

mouse **cursor** is **behind** all **windows** of dalamud

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Caliel666** [comment]
change it curseur matérial, both are fine.
