### ISSUE TITLE
[Suggestion]: Bigger Font Size Choices

### ISSUE THREAD

**Issue by scottmartin** [DelvUI/DelvUI#786]
### What's your suggestion?

It appears that the maximum font size you can create a preset for is 40. I'm vision impaired and like to make my unit frames be just a big percentage representation of health (i.e. 84.3). I can get the exact look I'm going for, but the 40 font is still too small for it to be completely usable for me. I'd like at least double that if possible.

Is there any way we can get even higher choices or even be able to type in the number we'd like?

Thank you very much for this plugin. It has given me a very easy way to make a more visible UI than the built-in one.

**Comment by Tischel** [comment]
Version 5.1 will support font sizes up to 100.
