### ISSUE TITLE
[Suggestion]: Weak selection indicator using controller

### ISSUE THREAD

**Issue by MikeZTM** [DelvUI/DelvUI#788]
### What's your suggestion?

Current party frame does not support weak party member selection status using controller (using D-Pad but not press A to confirm). It will show weak select as targeted.

This status should be shown as mouse over.

**Comment by MikeZTM** [comment]
Any news from this?

**Comment by vond82** [comment]
No devs use a controller and thus we dont really have much support for it, but from sounds of what youre describing i think it could be related to delvuis automatic mouseover as it "tricks" the game into thinking hovering = targeted, so this might be a side effect of that. Are the issues the same with delvuis automatic mouseover disabled?

**Comment by MikeZTM** [comment]
I have mouse over disabled when getting this behavior. 
Game logic did not change here as the target is still in weak select mode instead of targeted, but the party from from DelvUI shows the party member as targeted.

In fact, I'm guessing this controller weak selection may help building a real mouse over mode as game does have this feature built in.
When using controller weak selection, the game will not change target and thus not breaking melee progression.

**Comment by MikeZTM** [comment]
BTW for anyone that is not familiar with controller target selection:

Steps to select a party member:
0. initial state targeting boss
1. press up and down on d-pad
2. a highlight will show up on in-game party frame -- target is not yet selected, this is "weak selection stage"
3. press A to confirm selection
4. target changed to the selected member

If I cast any healing spell during the weak selection stage, it will be casted on the weak selection member and then it will cancel the weak selection stage and go back to initial state.
Before step 3 pressing A button the target will stay the same from initial state.
