### ISSUE TITLE
[Suggestion]: Add Astral Fire and Umbral Ice stacks in the mana bar for BLM.

### ISSUE THREAD

**Issue by tleon** [DelvUI/DelvUI#802]
### What's your suggestion?

Hey o/  I think it would be convenient to implement an AF & UI stacks display in the mana bar. 
Currently  it changes colors depending on the element you are in but you have no idea how many stacks you have. 

You could either add a number on the right innner side of the mana bar or another kind of indicator.  

Thanks a lot for all the work you already done. 

Best regards.

**Comment by vond82** [comment]
Has been added with 6.0
