### ISSUE TITLE
[Suggestion]: re-sizeable mouseover areas (with a border) for party frames.

### ISSUE THREAD

**Issue by Kuubi41** [DelvUI/DelvUI#832]
### What's your suggestion?

A suggestion, if possible,  to have a re-sizeable mouse over area for party frames for when the health bars are thin or small.
I was messing around, trying to create a "modern feeling" party list and ran into an issue where I have to precisely aim at the thin hp bar of the party members in order to target something. Would be nice to be able to have a larger area (maybe outlined by a border) for when you mouse over a party frame, similarly to what the in-game party list has, without having thick, brick-like hp bars

**Comment by vond82** [comment]
Added in 0.6.3.0
