### ISSUE TITLE
[Suggestion]: Click-through option for each status section

### ISSUE THREAD

**Issue by kaedys** [DelvUI/DelvUI#837]
### What's your suggestion?

Basically, I keep my buffs off to the side, but I have my debuffs and the Custom Effects sections large and relatively near the center of my screen, so I notice them.  I often end up clicking on them accidentally in combat when trying to right-click to spin my camera, which both prevents my camera from moving and potentially right-clicks off a buff I actually want to keep.  I realize that clickthrough would negate the ability to right-click off buffs, but that's partially why I want it as an option per status section, rather than some global option.  Debuffs can't be clicked off anyway (nor can any other status section except player buffs, for that matter), and my Custom Effects is for statuses I wouldn't want to click off anyway (ex. raid buffs).

Also, tangential, could we get an option for a bar-background behind the statuses that visualizes the duration?  Basically, same concept as the bars in the Job-Specific section for durationed effects, it would start as essentially just a colored square/rectangle behind the buff icon (extending beyond the edges enough to be easily visible, with maybe a size option?), and then the bar would shrink from one side to the other (I'd likely be using it top-to-bottom, equivalent to "grow direction: up" in the job section) until the debuff disappears. The mod Remind Me has this as an option, but that mod's options for which status effects you can display are exceptionally limited, so I'd love to see a similar feature with DelvUI's richer Custom Effects frame.

**Comment by kaedys** [comment]
Bump on this, I keep accidentally right-clicking on my Custom Status section, because I'm tracking more things in it on my Reaper, and not being able to turn my character when I expect to be able to.

**Comment by Tischel** [comment]
Setting added to status effect lists in v0.6.3.0

**Comment by kaedys** [comment]
Much appreciated!
