### ISSUE TITLE
[Suggestion]: Alternative "stance" display for Black Mage

### ISSUE THREAD

**Issue by kaedys** [DelvUI/DelvUI#838]
### What's your suggestion?

Currently, the Astral/Umbral "stance" status for BLM is layered on top of the mana bar.  It does not display stacks, and the duration is only displayed as text rather than a visual bar.  I'd like an option to display the Astral/Umbral status instead as a separate bar in that job frame, with the duration being the bar and both the duration and stacks being text displays on opposite sides of the bar (and probably with the same color behavior as the mana bar currently exhibits).  This would also require that the stance-based coloration on the Mana Bar be able to be disabled (currently, it cannot, though I suppose you could simply set the colors for all 3 to the same value).

**Comment by Tischel** [comment]
Umbral Ice / Astral Fire stacks were added in v0.6.0.0
