### ISSUE TITLE
[Bug]: Unchunked DRK mana bar has incorrect threshold

### ISSUE THREAD

**Issue by ForsakenMage** [DelvUI/DelvUI#846]
### What are you trying to do?

The unchunked DRK mana has incorrect thresholds for when it should change color to indicate when you have enough mana. 

### What is the expected behavior?

The mana bar should turn blue when reaching 3k mana.

### What actually happened?

The mana bar stays grey at 3k mana and only turns blue at 3400.

### Suggested solution

The threshold value for when the mana bar should turn blue was likely set at 1/3 of the max bar, this works when chunked since the chunked bar cuts off the last 1k, but when unchunked this makes the mana bar only turn blue at 3333. 

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v0.6.1.0
