### ISSUE TITLE
[Suggestion]: Different color for max HP when using color based on health values

### ISSUE THREAD

**Issue by boratintheuk** [DelvUI/DelvUI#851]
### What's your suggestion?

In ElvUI when setting unit frames to use color based on health value it goes from green to red, but at full health it goes gray.

Staring at green unit frames can be straining after awhile and a nice neutral color like gray would make them easier to look at.

While you could set full health color to gray or another neutral color with the current DelvUI setting, you would not a get a proper color scale.

Maybe just add a third color option? Low/High/Full instead of just Low/Full

**Comment by Tischel** [comment]
Implemented in 0.6.0.0
