### ISSUE TITLE
[Bug]: GCD indicator doesn't work for melee classes under lvl 30

### ISSUE THREAD

**Issue by EnderSyth** [DelvUI/DelvUI#855]
### What are you trying to do?

The GCD indicator which shows up for casting jobs below level 30 (Archer, Conjurer) does not show up when switching to melee jobs below level 30 (Rouge, Lancer). Even when forced to show the GCD indicator does not move to indicate the gcd.

### What is the expected behavior?

Casting skills should always show GCD indicator while enabled.
![image](https://user-images.githubusercontent.com/15831708/143324228-6fe179cb-346c-4937-b7a1-99cd254bd2e2.png)
![image](https://user-images.githubusercontent.com/15831708/143324239-f862dccf-3890-41be-810d-2db9fa84c26f.png)

### What actually happened?

GCD indicator doesn't show up. When forced to show it doesn't move.
![image](https://user-images.githubusercontent.com/15831708/143324197-d909b5fa-bbde-43ba-b3e2-1cf714bc3cb8.png)

### Suggested solution

Per confirming in discord this works with Melee jobs above level 30 so I'm assuming their solution can be implemented. Cali666 who I worked with in discord may provided a better guidance on a solution.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
Is this still an issue? I don't have any sub-30 melee classes to test with (suppose I could create an alt though once queues are better...) but looking at the code we don't do any checks for specific classes/jobs for the GCD indicator so it seems very odd to me

**Comment by EnderSyth** [comment]
> Is this still an issue? I don't have any sub-30 melee classes to test with (suppose I could create an alt though once queues are better...) but looking at the code we don't do any checks for specific classes/jobs for the GCD indicator so it seems very odd to me

Yes I just checked with Pugilist which is my only below 30 job left. I'm not familiar with the code but the fact it works for casters/ranged physical below 30 would make me think maybe there is so logic regarding GCD that depends on role types. Though why melee jobs/classes would be treated differently is beyond my abilities to speculate.

**Comment by Zeffuro** [comment]
> Is this still an issue? I don't have any sub-30 melee classes to test with (suppose I could create an alt though once queues are better...) but looking at the code we don't do any checks for specific classes/jobs for the GCD indicator so it seems very odd to me

We do, check the GCD Helper JobActionsIDs Dictionary

**Comment by vond82** [comment]
Yeah I'm stupid and forgot to check the Helper class, fixed for next version now anyway

**Comment by EnderSyth** [comment]
Awesome to hear thanks for resolving it!
