### ISSUE TITLE
[Bug]: BRD songs and DoTs are now 45s duration

### ISSUE THREAD

**Issue by bbck** [DelvUI/DelvUI#876]
### What are you trying to do?

Using the BRD job bars in Endwalker with the new longer durations
![image](https://user-images.githubusercontent.com/154447/146252414-9bfbb205-2ca0-497e-8ea1-fc984ce83d69.png)

### What is the expected behavior?

The song gauge, caustic bite, and stormbite bars should count down from 45s.

### What actually happened?

The countdown text is correct but the bar fill does not start decreasing until 30s remaining.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by TheResinger** [comment]
#878

**Comment by Tischel** [comment]
Fixed in 0.6.0.1
