### ISSUE TITLE
[Bug]: Ingame UI elements fall behind DelvUI elements.

### ISSUE THREAD

**Issue by Rho003** [DelvUI/DelvUI#877]
### What are you trying to do?

![order](https://user-images.githubusercontent.com/8780598/146258154-47fe930a-06e1-4146-88db-69ac1b0b4750.PNG)

Side menu of journal and duty finder does not go in front of DelvUI elements,.

Edit: With further testing, if you have your inventory in front of any DelvUI elements and mouseover anything in your bag just on top of the DelvUI elements, the DelvUI elements will fall in front of your bag until you move your mouse away from it .

### What is the expected behavior?

It should always fall behind ingame UI elements like inventory, map etc.
![no_mouseover](https://user-images.githubusercontent.com/8780598/146347480-86cdbe1c-adf0-46c3-888a-b15329eaee3f.png)
![inventory](https://user-images.githubusercontent.com/8780598/146349767-23e6a97f-4ec6-407d-b719-8097883f32af.png)

### What actually happened?

As you can see in the image, it DelvUI falls in front.
For the images below, place inventory above the bars, and just place your mouse over the stuff in your bag in front of DelvUI elements.
For the side menu of duty finder and journal, you just place it in front of DelvUI elements
![hp_above](https://user-images.githubusercontent.com/8780598/146347511-c48926e6-005d-44a3-8c0f-b47c2751573c.png)
![job_above](https://user-images.githubusercontent.com/8780598/146347532-ccd4f526-5dd1-4dd6-a92d-e23b544be6ea.png)
![hp_front](https://user-images.githubusercontent.com/8780598/146349793-74407ed9-5d7e-430a-bc30-482baba19f91.png)
![hp_above](https://user-images.githubusercontent.com/8780598/146349810-d02f7243-eb19-41cf-b2ed-265cb400a73d.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
DelvUI elements can only be clipped by one game window at a time. This is a technical decision/compromise otherwise things get really complicated.
When 2 game windows are on top of a DelvUI element, only one of them will be clipped.
The Duty Finder window is a special case because for some reason its basically 2 windows in one, and on top of that the bounds of those windows are "weird".
