### ISSUE TITLE
[Suggestion]: Player castbar drawn in layer over layer of GCD

### ISSUE THREAD

**Issue by Sservis** [DelvUI/DelvUI#885]
### What's your suggestion?

I'd like to put my castbar and GCD into the same screenspace, but currently castbar draws under GCD.  I can't come up with a usecase where you'd prefer to see GCD over castbar, but I definitely can think of cases where having castbar on top is useful.

Layout is cleaner if I can put them in the same location as then it's the same for all jobs. 

Alternatively, ability to manipulate element layers to stack items in custom orders.

**Comment by Tischel** [comment]
Added strata levels in v0.6.2.0
