### ISSUE TITLE
[Bug]: DelvUI HUD showing over the top of Chocobo Companion examine window

### ISSUE THREAD

**Issue by ryankhart** [DelvUI/DelvUI#896]
### What are you trying to do?

I think that the DelvUI HUD should be underneath all windows that can be opened and closed when outside of the HUD Layout screen.

### What is the expected behavior?

The above answer covers this too.

### What actually happened?

This screenshot shows that my Companion window is underneath the HUD.
![image](https://user-images.githubusercontent.com/3673962/146523697-72ece868-bc26-4155-87fb-c32513e51ab9.png)

### FFXIV Update

- [x] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by zoobsterswe** [comment]
I had the reverse problem. Something was covering DelvUI elements. Finally found that it was the inventory window that lay on top of DelvUi targetbar even if not open. Opening bags +  moving "solved" problem.

**Comment by Tischel** [comment]
Fixed in v0.6.1.1
