### ISSUE TITLE
[Bug]: Kardion not showing on party frame buffs

### ISSUE THREAD

**Issue by dcustic** [DelvUI/DelvUI#900]
### What are you trying to do?

![image](https://user-images.githubusercontent.com/7251275/146621068-68437f3e-bbc0-4605-b02a-91980e7430da.png)

ive whitelisted kardion

### What is the expected behavior?

Kardion on party frames 

in this pic u see the tank has kardion but its not showing on pt frames

![image](https://user-images.githubusercontent.com/7251275/146621109-4abaca5b-6dc3-433d-b8fb-b3c008a09ad0.png)

### What actually happened?

buff not showing

### Suggested solution

buff showing

### Logs

```shell
not relevant i belive
```

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
Its a permanent buff so you need to enable that setting for party buffs and it will work just fine

**Comment by dcustic** [comment]
Aah, ok, thanks for reviewing the issue
