### ISSUE TITLE
[Bug]: NPC target removes all text

### ISSUE THREAD

**Issue by wigoor** [DelvUI/DelvUI#901]
### What are you trying to do?

Im trying to setup my "target" frame to look the same as my player frame. The problem appears when i try to target a friendly NPC. It seem they do not have any HP? and that breaks the the text im trying to use.

[health:current]          [name:first] - [level]            [mana:current-short]

If i remove [health:current] from the "Text" it starts to work for NPC's but its not the desired effect i want on other targets.

![image](https://user-images.githubusercontent.com/26260419/146652155-5acd0d76-6d31-488b-ba3c-169e229ff47e.png)

Same thing applies to Minions and other "non-hp" targets?
![image](https://user-images.githubusercontent.com/26260419/146652566-fcfa9974-6f9f-475d-90c0-7400c9b33bd2.png)

### What is the expected behavior?

I expect it to work the same as it does on players.

### What actually happened?

All text disappears on NPC targets.

### Suggested solution

I'd like it to show the NPC HP or maybe something like "100" to just have a number representation if they don't actually have any HP. Another solution to the problem would be if there was more text options like the "custom" fields in Elvui, then I could make the health, name and power texts be split and have different colors etc.
![image](https://user-images.githubusercontent.com/26260419/146652454-90032a78-7b39-4c2f-ac42-9b6a4a8bbb65.png)

Im trying to recreate my Elvui profile
![image](https://user-images.githubusercontent.com/26260419/146652365-30a0a0a0-f8a8-4b30-ba8c-b8d5a077371a.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
You have "Hide Health if Possible" checked, which is why it hides that label where you have name+health+mana so it's not a bug but a feature you might not have noticed you had enabled. :)
