### ISSUE TITLE
[Bug]: Rekindle (SMN Phoenix Spell) doesn't work on Mouseover Automatic Mode

### ISSUE THREAD

**Issue by Hayato2846** [DelvUI/DelvUI#909]
### What are you trying to do?

See title's description. Phoenix pet always casts Rekindle on self when mouse is over a party member's frame.

[See here: ](https://discord.com/channels/878296899331973120/878300884143071302/922519699105906708)

### What is the expected behavior?

Rekindle's target is the party member.

### What actually happened?

Rekindle's casted on self.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Fixed in v0.6.1.1
