### ISSUE TITLE
[Bug]: "Missing health color" shines through transparent bars

### ISSUE THREAD

**Issue by wigoor** [DelvUI/DelvUI#923]
### What are you trying to do?

Trying to set a "Missing Health Color" while having a Health color that is slightly transparent.

(also the "Missing Health Color" option is missing from party frames, would be nice to have so you can use transparent frames, can get the same effect with "background color" if i DONT use transparent frames for party.)

### What is the expected behavior?

I expect the "Missing Health Color" option to only show on the "missing health" part of the frame and not be active/visible behind the Health color.

### What actually happened?

Since the last update something changed with player/party frame, it now Always have the "missing health color" active behind the health color, making it shine through if you want to have a transparent effect on your unitframes.

https://user-images.githubusercontent.com/26260419/147228789-9355e3a9-25e8-481c-a3fd-eaced73d19ea.mp4

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
@lichie567 maybe you could look at this since you should know it best?

**Comment by Tischel** [comment]
Fixed in v0.6.1.2

**Comment by vond82** [comment]
Fixed in 0.6.1.2
