### ISSUE TITLE
[Bug]: Party frames borders

### ISSUE THREAD

**Issue by Murkchan** [DelvUI/DelvUI#928]
Immediately I apologize for google translation

Party frames break if their border is close to the edges. In this case, mouseover also does not work.

It looks like this with open and closed settings. 
![image](https://user-images.githubusercontent.com/26253455/147381620-d653bdfe-99b3-4ea0-bda6-b06ac25ac3f0.png)
![image](https://user-images.githubusercontent.com/26253455/147381628-33cac60e-d141-4ad4-9342-023e4163329b.png)

**Comment by Tischel** [comment]
Fixed in v0.6.2.0
