### ISSUE TITLE
[Suggestion]: Way to force Mana Bar under icon's like the health bar dose.

### ISSUE THREAD

**Issue by KnightLen** [DelvUI/DelvUI#931]
### What's the issue?

Hi, first off THANK YOU so much for Delv UI such an amazing project. So to the problem I am trying to correct, I would like a way to layer the MP bar on both the Party frame's and Other frames like self/target so that its on the same layer as the health bar. 

![image](https://user-images.githubusercontent.com/96664904/147392640-f6001640-2f11-4eb5-b6cb-53ae60b156ec.png)

So if that worked you can see the mana bars are sitting on top of the Role Icon, would like to be able to have the roll Icon sit over that as well. Now if I missed some setting and I may have is this possible?

Thank you again for your time :)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
Added with strata levels in v0.6.2.0
