### ISSUE TITLE
[Suggestion]: fill healthbar by missing health on party healthbars + move shields

### ISSUE THREAD

**Issue by mkarer** [DelvUI/DelvUI#932]
### What's your suggestion?

I don't think there's currently an option to fill the bar by missing health instead of current health (I think there's one for the non-party-unitframes though):

![missinghealth+shield](https://user-images.githubusercontent.com/1595346/147396164-3c6b2122-4a68-4c9c-92aa-1d418fdaa11e.png)

Less HP = Larger bar + brighter color. Makes it easier to spot the party member that needs the most attention. Also having shield+overshield on the same spot seems more logical to me, but maybe I'm just weird.

(This was just quickly thrown together by modifying BarUtilities.GetShieldForeground and using it for party aswell + adding a settings to allow changing fill direction + another one to fill by missing hp. But there's propably a reason why you're not using GetShieldForeground for the party aswell I assume? Also my implementation is buggy because I suck.)

**Comment by Tischel** [comment]
Added in v0.6.2.0

**Comment by mkarer** [comment]
> Added in v0.6.2.0

Thank you very much @Tischel, but I think I'm too stupid to set it up like that 😕 (or I didn't explain well enough).

This is how it's supposed to look like (without the smooth transition bug):

https://user-images.githubusercontent.com/1595346/147868180-6ca8db67-d2ee-4fa7-9d3b-c9ad3fb6f5e4.mp4

Instead of using the current health amount I'd like to have it fill the bar by the amount of missing health."Missing Health Color" would then be used for current health and "Color Based On Health Value" for the missing amount/filled part of the bar.
