### ISSUE TITLE
[Suggestion]: Dancer Job for Technical Finish 120 CD on cooldown tracker

### ISSUE THREAD

**Issue by BadBuns** [DelvUI/DelvUI#936]
### What's your suggestion?

i noticed that the technical step from dancer is not on the tracked cooldowns, i don't know if this is known yet or not, but i thought i'd point it out, would be neat to be available to see that too along all other CD's . love the UI, first time doing a suggestion for something

**Comment by Tischel** [comment]
This one is tricky because it needs to track the effect duration of technical finish, but the cooldown of technical step. So it's like a special case.
I'll get to it eventually.

**Comment by vond82** [comment]
Added in 0.6.3.0
