### ISSUE TITLE
[Bug]: Dancer job bar proc indicators

### ISSUE THREAD

**Issue by kaedys** [DelvUI/DelvUI#945]
### What are you trying to do?

The Dancer job gauge still has elements for all four first-level procs (Flourishing Cascade, Flourishing Fountain, Flourishing Windmill, Flourishing Shower), but Dancer only has _two_ first-level procs now: Flourishing Symmetry (granted by Cascade and Windmill, usable on Reverse Cascade or Rising Windmill) and Flourishing Flow (granted by Fountain and Bladeshower, usable on Fountainfall or Bloodshower).  The indicators do light up for the procs, but are duplicated (ie. when you gain Flourishing Symmetry, both the Cascade and Windmill indicators light up).  In addition, the Enable/Disable button for Windmill and Shower do not appear to function, the indicators still show up even when disabled.  I had to set both to 0% alpha as a work-around.

### What is the expected behavior?

There should only be two indicators now, rather than four, and the enable/disable should work as expected for them.

### What actually happened?

See above.

### Suggested solution

See above.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
This is fixed already for the next version (still 4 available but disable works). Should go live within the next 24h hopefully.
