### ISSUE TITLE
[Suggestion]: Customizable MO area for party frames

### ISSUE THREAD

**Issue by kindasussy** [DelvUI/DelvUI#946]
### What's your suggestion?

Suggestion for a customizable MO area in the party frames.
For people like me who have smaller HP bars this would be a very nice QoL feature. For example like the red box you can see in the screenshot.
A visible border when hovering over it would also be good.

![l](https://user-images.githubusercontent.com/96928005/147841021-059f23f4-6558-424f-a5ea-b5bee013bfbc.png)

**Comment by Tischel** [comment]
Added in v0.6.3.0
