### ISSUE TITLE
[Suggestion]: BLM - Enochian Countdown

### ISSUE THREAD

**Issue by BlackWyvern** [DelvUI/DelvUI#964]
### What's your suggestion?

Currently, the Enochian bar only tracks the time until the next polygot tick. It does not however allow us to track the time left on enochian itself. Important thing to track if you're slidecasting in a mobile fight.

Request is to have the enochian bar to track Enochian's duration from last stance change, the polyglot bar to track time until polyglot charge, and then a 'polyglot pips' or 'polyglot charge bar' for displaying the charges.

**Comment by Tischel** [comment]
That is being tracked in the custom mana bar. Won't duplicate this functionallity.
