### ISSUE TITLE
[Bug]: Missing health does not fade with Out-of-Range

### ISSUE THREAD

**Issue by wigoor** [DelvUI/DelvUI#965]
### What are you trying to do?

Missing Health Color does not care if you have out-of-range fade on or not.

### What is the expected behavior?

I expect the full Party frame to fade with range, not only "current hp".

### What actually happened?

The health fades, but "Missing health" keeps at full alpha.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
Fixed in v1.0.0.0
