### ISSUE TITLE
[Bug]: Missing Target/targets-target Out-of-range option

### ISSUE THREAD

**Issue by wigoor** [DelvUI/DelvUI#966]
### What are you trying to do?

Trying to set Out of Range alpha for target/targets-target. Dosent seem to have an option.

### What is the expected behavior?

I expect all frames except Player frame to have the same Out-of-range fade effect/option.

### What actually happened?

Missing setting.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
Well that's not a bug but a feature request :) This is only a thing in the party frames currently as they are completely separated from the unit frames.

**Comment by vond82** [comment]
Added in v1.0.0.0
