### ISSUE TITLE
[Bug]: Tooltip of buffs and debuffs only show "???"  on Chinese client.

### ISSUE THREAD

**Issue by k99k5** [DelvUI/DelvUI#976]
### What are you trying to do?

Tooltip of buffs and debuffs only show "???"  on Chinese client.
![}2{ OGDTB5VZ4YD@`{9PHJ](https://user-images.githubusercontent.com/18001536/149162027-10587262-ad7e-478a-ab33-ba0ebb925aa1.png)

### What is the expected behavior?

Tooltip of buffs and debuffs show the title and text.
![G0YKYS4YJC7 `81SHK5 QB](https://user-images.githubusercontent.com/18001536/149162396-a73e4ff7-41b1-41c0-bd58-03e97c8376b2.png)

### What actually happened?

Tooltip of buffs and debuffs only show "???"  on Chinese client.
![}2{ OGDTB5VZ4YD@`{9PHJ](https://user-images.githubusercontent.com/18001536/149162027-10587262-ad7e-478a-ab33-ba0ebb925aa1.png)

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Tischel** [comment]
You need to add a font that support chinese characters.

**Comment by k99k5** [comment]
> You need to add a font that supports chinese characters. The default one doesn't have them.

only buffs and debuffs not supports chinese characters.

**Comment by hyou03** [comment]
> > 您需要添加支持汉字的字体。默认的没有它们。
> 
> @Tischel 只有增益和减益不支持汉字。
在Misc > Tooltips 修改字体就可以了
