### ISSUE TITLE
[Help wanted]: 

### ISSUE THREAD

**Issue by Yubtini** [DelvUI/DelvUI#989]
### What's the issue?

Default UI elements now showing up behind all of DelvUI's elements after the most recent update. Wondering if there is some way to fix that throught the config. Thanks.

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
This was in the changelog for v1.0.0.0, and is answered in the FAQ on our Discord (https://discord.gg/delvui if you’re not there), but what you need to do is enable Window Clipping in Misc > Window Clipping :)

**Comment by Yubtini** [comment]
Thanks so much!
