### ISSUE TITLE
[Help wanted]: How to display the default job bar

### ISSUE THREAD

**Issue by SolarisXYZ** [DelvUI/DelvUI#999]
### What's the issue?

For some jobs, I want to use the default job bars rather than the DelvUI job bar.  

I'm not sure if it's feature or not, but I cannot find it in the config/setting. 

If not, can it be made into a suggestion to be added at a later date. 

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by vond82** [comment]
Misc > HUD Options > uncheck the Hide Default Job Bars setting, need separate profiles between jobs where you use delvui and default tho
